// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/components/table_row.def.rs".

#pragma once

#include "../collection.hpp"
#include "../encodings/table_value.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace arrow {
    class Array;
    class DataType;
    class ListBuilder;
} // namespace arrow

namespace rerun::components {
    /// **Component**: One row of a `archetypes::DataTable`, in schema column order.
    ///
    /// Checkbox cells use `Number(0.0)` for unchecked and `Number(1.0)` for checked.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableRow {
        rerun::Collection<rerun::encodings::TableValue> values;

      public:
        TableRow() = default;

        TableRow(rerun::Collection<rerun::encodings::TableValue> values_)
            : values(std::move(values_)) {}

        TableRow& operator=(rerun::Collection<rerun::encodings::TableValue> values_) {
            values = std::move(values_);
            return *this;
        }
    };
} // namespace rerun::components

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<components::TableRow> {
        static constexpr std::string_view ComponentType = "rerun.components.TableRow";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::components::TableRow` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::TableRow* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::ListBuilder* builder, const components::TableRow* elements, size_t num_elements
        );
    };
} // namespace rerun
