// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/components/table_column.def.rs".

#pragma once

#include "../encodings/table_buffer.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace rerun::components {
    /// **Component**: One column of a `archetypes::DataTable`.
    ///
    /// Numeric data must be a one-dimensional tensor.
    /// Checkbox columns use numeric zero for unchecked and one for checked.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableColumn {
        rerun::encodings::TableBuffer values;

      public:
        TableColumn() = default;

        TableColumn(rerun::encodings::TableBuffer values_) : values(std::move(values_)) {}

        TableColumn& operator=(rerun::encodings::TableBuffer values_) {
            values = std::move(values_);
            return *this;
        }

        /// Cast to the underlying TableBuffer encoding
        operator rerun::encodings::TableBuffer() const {
            return values;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::encodings::TableBuffer) == sizeof(components::TableColumn));

    /// \private
    template <>
    struct Loggable<components::TableColumn> {
        static constexpr std::string_view ComponentType = "rerun.components.TableColumn";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type() {
            return Loggable<rerun::encodings::TableBuffer>::arrow_data_type();
        }

        /// Serializes an array of `rerun::components::TableColumn` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::TableColumn* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::encodings::TableBuffer>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::encodings::TableBuffer>::to_arrow(
                    &instances->values,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
