// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/components/table_schema.def.rs".

#pragma once

#include "../encodings/table_schema.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <utility>

namespace rerun::components {
    /// **Component**: The ordered groups and columns of a `archetypes::DataTable`.
    ///
    /// Group IDs must be unique within the table, and column IDs must be unique within their group.
    /// Metadata and values are independent components; log compatible schema and data together when changing the structure.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableSchema {
        rerun::encodings::TableSchema schema;

      public:
        TableSchema() = default;

        TableSchema(rerun::encodings::TableSchema schema_) : schema(std::move(schema_)) {}

        TableSchema& operator=(rerun::encodings::TableSchema schema_) {
            schema = std::move(schema_);
            return *this;
        }

        /// Cast to the underlying TableSchema encoding
        operator rerun::encodings::TableSchema() const {
            return schema;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::encodings::TableSchema) == sizeof(components::TableSchema));

    /// \private
    template <>
    struct Loggable<components::TableSchema> {
        static constexpr std::string_view ComponentType = "rerun.components.TableSchema";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type() {
            return Loggable<rerun::encodings::TableSchema>::arrow_data_type();
        }

        /// Serializes an array of `rerun::components::TableSchema` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::TableSchema* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::encodings::TableSchema>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::encodings::TableSchema>::to_arrow(
                    &instances->schema,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
