// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/components/table_schema.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Component**: The ordered groups and columns of a [`archetypes::DataTable`][crate::archetypes::DataTable].
///
/// Group IDs must be unique within the table, and column IDs must be unique within their group.
/// Metadata and values are independent components; log compatible schema and data together when changing the structure.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, PartialEq, ::re_byte_size::SizeBytes)]
pub struct TableSchema(pub crate::encodings::TableSchema);

impl ::re_types_core::WrapperComponent for TableSchema {
    type Encoding = crate::encodings::TableSchema;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.TableSchema".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Encoding {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(TableSchema);

impl<T: Into<crate::encodings::TableSchema>> From<T> for TableSchema {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::encodings::TableSchema> for TableSchema {
    #[inline]
    fn borrow(&self) -> &crate::encodings::TableSchema {
        &self.0
    }
}

impl std::ops::Deref for TableSchema {
    type Target = crate::encodings::TableSchema;

    #[inline]
    fn deref(&self) -> &crate::encodings::TableSchema {
        &self.0
    }
}

impl std::ops::DerefMut for TableSchema {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::encodings::TableSchema {
        &mut self.0
    }
}
