// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/components/table_column.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Component**: One column of a [`archetypes::DataTable`][crate::archetypes::DataTable].
///
/// Numeric data must be a one-dimensional tensor.
/// Checkbox columns use numeric zero for unchecked and one for checked.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, ::re_byte_size::SizeBytes)]
pub struct TableColumn(pub crate::encodings::TableBuffer);

impl ::re_types_core::WrapperComponent for TableColumn {
    type Encoding = crate::encodings::TableBuffer;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.TableColumn".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Encoding {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(TableColumn);

impl<T: Into<crate::encodings::TableBuffer>> From<T> for TableColumn {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::encodings::TableBuffer> for TableColumn {
    #[inline]
    fn borrow(&self) -> &crate::encodings::TableBuffer {
        &self.0
    }
}

impl std::ops::Deref for TableColumn {
    type Target = crate::encodings::TableBuffer;

    #[inline]
    fn deref(&self) -> &crate::encodings::TableBuffer {
        &self.0
    }
}

impl std::ops::DerefMut for TableColumn {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::encodings::TableBuffer {
        &mut self.0
    }
}
