[package]
name = "re_view_datatable"
authors.workspace = true
description = "A dense grouped DataTable view."
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true
include.workspace = true

[lints]
workspace = true

[dependencies]
re_byte_size.workspace = true
re_chunk.workspace = true
re_chunk_store.workspace = true
re_format.workspace = true
re_log_types.workspace = true
re_sdk_types.workspace = true
re_ui.workspace = true
re_view.workspace = true
re_viewer_context.workspace = true

arrow.workspace = true
egui.workspace = true
egui_table.workspace = true
rayon.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
mimalloc.workspace = true
re_memory.workspace = true
re_test_context.workspace = true
re_test_viewport.workspace = true
re_viewport_blueprint.workspace = true
