// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_column_schema.def.rs".

#include "table_column_schema.hpp"

#include "table_column_option.hpp"

#include <arrow/builder.h>
#include <arrow/type_fwd.h>

namespace rerun::encodings {}

namespace rerun {
    const std::shared_ptr<arrow::DataType>& Loggable<encodings::TableColumnSchema>::arrow_data_type(
    ) {
        static const auto datatype = arrow::struct_({
            arrow::field("id", arrow::utf8(), false),
            arrow::field("label", arrow::utf8(), false),
            arrow::field(
                "column_dropdown",
                arrow::list(arrow::field(
                    "item",
                    Loggable<rerun::encodings::TableColumnOption>::arrow_data_type(),
                    false
                )),
                true
            ),
            arrow::field("checkbox", arrow::boolean(), true),
            arrow::field("heatmap", arrow::boolean(), true),
        });
        return datatype;
    }

    Result<std::shared_ptr<arrow::Array>> Loggable<encodings::TableColumnSchema>::to_arrow(
        const encodings::TableColumnSchema* instances, size_t num_instances
    ) {
        // TODO(andreas): Allow configuring the memory pool.
        arrow::MemoryPool* pool = arrow::default_memory_pool();
        auto datatype = arrow_data_type();

        ARROW_ASSIGN_OR_RAISE(auto builder, arrow::MakeBuilder(datatype, pool))
        if (instances && num_instances > 0) {
            RR_RETURN_NOT_OK(Loggable<encodings::TableColumnSchema>::fill_arrow_array_builder(
                static_cast<arrow::StructBuilder*>(builder.get()),
                instances,
                num_instances
            ));
        }
        std::shared_ptr<arrow::Array> array;
        ARROW_RETURN_NOT_OK(builder->Finish(&array));
        return array;
    }

    rerun::Error Loggable<encodings::TableColumnSchema>::fill_arrow_array_builder(
        arrow::StructBuilder* builder, const encodings::TableColumnSchema* elements,
        size_t num_elements
    ) {
        if (builder == nullptr) {
            return rerun::Error(ErrorCode::UnexpectedNullArgument, "Passed array builder is null.");
        }
        if (elements == nullptr) {
            return rerun::Error(
                ErrorCode::UnexpectedNullArgument,
                "Cannot serialize null pointer to arrow array."
            );
        }

        {
            auto field_builder = static_cast<arrow::StringBuilder*>(builder->field_builder(0));
            ARROW_RETURN_NOT_OK(field_builder->Reserve(static_cast<int64_t>(num_elements)));
            for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
                ARROW_RETURN_NOT_OK(field_builder->Append(elements[elem_idx].id));
            }
        }
        {
            auto field_builder = static_cast<arrow::StringBuilder*>(builder->field_builder(1));
            ARROW_RETURN_NOT_OK(field_builder->Reserve(static_cast<int64_t>(num_elements)));
            for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
                ARROW_RETURN_NOT_OK(field_builder->Append(elements[elem_idx].label));
            }
        }
        {
            auto field_builder = static_cast<arrow::ListBuilder*>(builder->field_builder(2));
            auto value_builder = static_cast<arrow::StructBuilder*>(field_builder->value_builder());
            ARROW_RETURN_NOT_OK(field_builder->Reserve(static_cast<int64_t>(num_elements)));
            ARROW_RETURN_NOT_OK(value_builder->Reserve(static_cast<int64_t>(num_elements) * 1));

            for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
                const auto& element = elements[elem_idx];
                if (element.column_dropdown.has_value()) {
                    ARROW_RETURN_NOT_OK(field_builder->Append());
                    if (element.column_dropdown.value().data()) {
                        RR_RETURN_NOT_OK(
                            Loggable<rerun::encodings::TableColumnOption>::fill_arrow_array_builder(
                                value_builder,
                                element.column_dropdown.value().data(),
                                element.column_dropdown.value().size()
                            )
                        );
                    }
                } else {
                    ARROW_RETURN_NOT_OK(field_builder->AppendNull());
                }
            }
        }
        {
            auto field_builder = static_cast<arrow::BooleanBuilder*>(builder->field_builder(3));
            ARROW_RETURN_NOT_OK(field_builder->Reserve(static_cast<int64_t>(num_elements)));
            for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
                const auto& element = elements[elem_idx];
                if (element.checkbox.has_value()) {
                    ARROW_RETURN_NOT_OK(field_builder->Append(element.checkbox.value()));
                } else {
                    ARROW_RETURN_NOT_OK(field_builder->AppendNull());
                }
            }
        }
        {
            auto field_builder = static_cast<arrow::BooleanBuilder*>(builder->field_builder(4));
            ARROW_RETURN_NOT_OK(field_builder->Reserve(static_cast<int64_t>(num_elements)));
            for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
                const auto& element = elements[elem_idx];
                if (element.heatmap.has_value()) {
                    ARROW_RETURN_NOT_OK(field_builder->Append(element.heatmap.value()));
                } else {
                    ARROW_RETURN_NOT_OK(field_builder->AppendNull());
                }
            }
        }
        ARROW_RETURN_NOT_OK(builder->AppendValues(static_cast<int64_t>(num_elements), nullptr));

        return Error::ok();
    }
} // namespace rerun
