// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_group.def.rs".

#pragma once

#include "../collection.hpp"
#include "../result.hpp"
#include "table_column_schema.hpp"

#include <cstdint>
#include <memory>
#include <optional>
#include <string>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace rerun::encodings {
    /// **Encoding**: A group of adjacent columns in a `archetypes::DataTable`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableGroup {
        /// Stable identity for this group, independent of its labels.
        std::string id;

        /// Primary group header text.
        std::string primary_group;

        /// Optional subgroup header text.
        std::optional<std::string> sub_group;

        /// Columns in display and data order.
        rerun::Collection<rerun::encodings::TableColumnSchema> columns;

      public:
        TableGroup() = default;
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::TableGroup> {
        static constexpr std::string_view ComponentType = "rerun.encodings.TableGroup";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::TableGroup` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::TableGroup* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const encodings::TableGroup* elements,
            size_t num_elements
        );
    };
} // namespace rerun
