// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_buffer.def.rs".

#include "table_buffer.hpp"

#include "tensor_data.hpp"

#include <arrow/builder.h>
#include <arrow/type_fwd.h>

namespace rerun::encodings {}

namespace rerun {
    const std::shared_ptr<arrow::DataType>& Loggable<encodings::TableBuffer>::arrow_data_type() {
        static const auto datatype = arrow::dense_union({
            arrow::field("_null_markers", arrow::null(), true, nullptr),
            arrow::field(
                "Numeric",
                Loggable<rerun::encodings::TensorData>::arrow_data_type(),
                false
            ),
            arrow::field("Text", arrow::list(arrow::field("item", arrow::utf8(), false)), false),
        });
        return datatype;
    }

    Result<std::shared_ptr<arrow::Array>> Loggable<encodings::TableBuffer>::to_arrow(
        const encodings::TableBuffer* instances, size_t num_instances
    ) {
        // TODO(andreas): Allow configuring the memory pool.
        arrow::MemoryPool* pool = arrow::default_memory_pool();
        auto datatype = arrow_data_type();

        ARROW_ASSIGN_OR_RAISE(auto builder, arrow::MakeBuilder(datatype, pool))
        if (instances && num_instances > 0) {
            RR_RETURN_NOT_OK(Loggable<encodings::TableBuffer>::fill_arrow_array_builder(
                static_cast<arrow::DenseUnionBuilder*>(builder.get()),
                instances,
                num_instances
            ));
        }
        std::shared_ptr<arrow::Array> array;
        ARROW_RETURN_NOT_OK(builder->Finish(&array));
        return array;
    }

    rerun::Error Loggable<encodings::TableBuffer>::fill_arrow_array_builder(
        arrow::DenseUnionBuilder* builder, const encodings::TableBuffer* elements,
        size_t num_elements
    ) {
        if (builder == nullptr) {
            return rerun::Error(ErrorCode::UnexpectedNullArgument, "Passed array builder is null.");
        }
        if (elements == nullptr) {
            return rerun::Error(
                ErrorCode::UnexpectedNullArgument,
                "Cannot serialize null pointer to arrow array."
            );
        }

        ARROW_RETURN_NOT_OK(builder->Reserve(static_cast<int64_t>(num_elements)));
        for (size_t elem_idx = 0; elem_idx < num_elements; elem_idx += 1) {
            const auto& union_instance = elements[elem_idx];
            ARROW_RETURN_NOT_OK(builder->Append(static_cast<int8_t>(union_instance.get_union_tag()))
            );

            auto variant_index = static_cast<int>(union_instance.get_union_tag());
            auto variant_builder_untyped = builder->child_builder(variant_index).get();

            using TagType = encodings::detail::TableBufferTag;
            switch (union_instance.get_union_tag()) {
                case TagType::None: {
                    ARROW_RETURN_NOT_OK(variant_builder_untyped->AppendNull());
                } break;
                case TagType::Numeric: {
                    auto variant_builder =
                        static_cast<arrow::StructBuilder*>(variant_builder_untyped);
                    RR_RETURN_NOT_OK(
                        Loggable<rerun::encodings::TensorData>::fill_arrow_array_builder(
                            variant_builder,
                            &union_instance.get_union_data().numeric,
                            1
                        )
                    );
                } break;
                case TagType::Text: {
                    auto variant_builder =
                        static_cast<arrow::ListBuilder*>(variant_builder_untyped);
                    ARROW_RETURN_NOT_OK(variant_builder->Append());
                    auto value_builder =
                        static_cast<arrow::StringBuilder*>(variant_builder->value_builder());
                    ARROW_RETURN_NOT_OK(value_builder->AppendValues(
                        union_instance.get_union_data().text.data(),
                        static_cast<int64_t>(union_instance.get_union_data().text.size())
                    ));
                } break;
                default:
                    assert(false && "unreachable");
            }
        }

        return Error::ok();
    }
} // namespace rerun
