// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_sort_scope.def.rs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class UInt8Type;
    using UInt8Builder = NumericBuilder<UInt8Type>;
} // namespace arrow

namespace rerun::encodings {
    /// **Encoding**: How sorting reorders rows in a `archetypes::DataTable`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    enum class TableSortScope : uint8_t {

        /// Sort all columns together.
        Table = 1,

        /// Sort each schema group independently.
        Subgroup = 2,
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::TableSortScope> {
        static constexpr std::string_view ComponentType = "rerun.encodings.TableSortScope";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::TableSortScope` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::TableSortScope* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::UInt8Builder* builder, const encodings::TableSortScope* elements,
            size_t num_elements
        );
    };
} // namespace rerun
