// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_buffer.def.rs".

#pragma once

#include "../collection.hpp"
#include "../result.hpp"
#include "tensor_data.hpp"

#include <cstdint>
#include <cstring>
#include <memory>
#include <new>
#include <string>
#include <utility>

namespace arrow {
    class Array;
    class DataType;
    class DenseUnionBuilder;
} // namespace arrow

namespace rerun::encodings {
    namespace detail {
        /// \private
        enum class TableBufferTag : uint8_t {
            /// Having a special empty state makes it possible to implement move-semantics. We need to be able to leave the object in a state which we can run the destructor on.
            None = 0,
            Numeric,
            Text,
        };

        /// \private
        union TableBufferData {
            /// Numeric values with a shape and a typed buffer.
            rerun::encodings::TensorData numeric;

            /// A one-dimensional array of UTF-8 text values.
            rerun::Collection<std::string> text;

            TableBufferData() {
                std::memset(reinterpret_cast<void*>(this), 0, sizeof(TableBufferData));
            }

            ~TableBufferData() {}

            void swap(TableBufferData& other) noexcept {
                // This bitwise swap would fail for self-referential types, but we don't have any of those.
                char temp[sizeof(TableBufferData)];
                void* otherbytes = reinterpret_cast<void*>(&other);
                void* thisbytes = reinterpret_cast<void*>(this);
                std::memcpy(temp, thisbytes, sizeof(TableBufferData));
                std::memcpy(thisbytes, otherbytes, sizeof(TableBufferData));
                std::memcpy(otherbytes, temp, sizeof(TableBufferData));
            }
        };
    } // namespace detail

    /// **Encoding**: A numeric tensor or an array of text values for table data.
    ///
    /// The numeric variant preserves its shape and numeric element type without
    /// wrapping each element in a `encodings::TableValue`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableBuffer {
        TableBuffer() : _tag(detail::TableBufferTag::None) {}

        /// Copy constructor
        TableBuffer(const TableBuffer& other) : _tag(other._tag) {
            switch (other._tag) {
                case detail::TableBufferTag::Numeric: {
                    using TypeAlias = rerun::encodings::TensorData;
                    new (&_data.numeric) TypeAlias(other._data.numeric);
                } break;
                case detail::TableBufferTag::Text: {
                    using TypeAlias = rerun::Collection<std::string>;
                    new (&_data.text) TypeAlias(other._data.text);
                } break;
                case detail::TableBufferTag::None: {
                } break;
                default:
                    assert(false && "unreachable");
            }
        }

        TableBuffer& operator=(const TableBuffer& other) noexcept {
            TableBuffer tmp(other);
            this->swap(tmp);
            return *this;
        }

        TableBuffer(TableBuffer&& other) noexcept : TableBuffer() {
            this->swap(other);
        }

        TableBuffer& operator=(TableBuffer&& other) noexcept {
            this->swap(other);
            return *this;
        }

        ~TableBuffer() {
            switch (this->_tag) {
                case detail::TableBufferTag::None: {
                    // Nothing to destroy
                } break;
                case detail::TableBufferTag::Numeric: {
                    using TypeAlias = rerun::encodings::TensorData;
                    _data.numeric.~TypeAlias();
                } break;
                case detail::TableBufferTag::Text: {
                    using TypeAlias = rerun::Collection<std::string>;
                    _data.text.~TypeAlias();
                } break;
                default:
                    assert(false && "unreachable");
            }
        }

        void swap(TableBuffer& other) noexcept {
            std::swap(this->_tag, other._tag);
            this->_data.swap(other._data);
        }

        /// Numeric values with a shape and a typed buffer.
        TableBuffer(rerun::encodings::TensorData numeric) : TableBuffer() {
            *this = TableBuffer::numeric(std::move(numeric));
        }

        /// A one-dimensional array of UTF-8 text values.
        TableBuffer(rerun::Collection<std::string> text) : TableBuffer() {
            *this = TableBuffer::text(std::move(text));
        }

        /// Numeric values with a shape and a typed buffer.
        static TableBuffer numeric(rerun::encodings::TensorData numeric) {
            TableBuffer self;
            self._tag = detail::TableBufferTag::Numeric;
            new (&self._data.numeric) rerun::encodings::TensorData(std::move(numeric));
            return self;
        }

        /// A one-dimensional array of UTF-8 text values.
        static TableBuffer text(rerun::Collection<std::string> text) {
            TableBuffer self;
            self._tag = detail::TableBufferTag::Text;
            new (&self._data.text) rerun::Collection<std::string>(std::move(text));
            return self;
        }

        /// Return a pointer to numeric if the union is in that state, otherwise `nullptr`.
        const rerun::encodings::TensorData* get_numeric() const {
            if (_tag == detail::TableBufferTag::Numeric) {
                return &_data.numeric;
            } else {
                return nullptr;
            }
        }

        /// Return a pointer to text if the union is in that state, otherwise `nullptr`.
        const rerun::Collection<std::string>* get_text() const {
            if (_tag == detail::TableBufferTag::Text) {
                return &_data.text;
            } else {
                return nullptr;
            }
        }

        /// \private
        const detail::TableBufferData& get_union_data() const {
            return _data;
        }

        /// \private
        detail::TableBufferTag get_union_tag() const {
            return _tag;
        }

      private:
        detail::TableBufferTag _tag;
        detail::TableBufferData _data;
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::TableBuffer> {
        static constexpr std::string_view ComponentType = "rerun.encodings.TableBuffer";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::TableBuffer` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::TableBuffer* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::DenseUnionBuilder* builder, const encodings::TableBuffer* elements,
            size_t num_elements
        );
    };
} // namespace rerun
