// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_column_schema.def.rs".

#pragma once

#include "../collection.hpp"
#include "../result.hpp"
#include "table_column_option.hpp"

#include <cstdint>
#include <memory>
#include <optional>
#include <string>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace rerun::encodings {
    /// **Encoding**: Header and presentation metadata for one `archetypes::DataTable` column.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableColumnSchema {
        /// Stable identity within the group, independent of the displayed header.
        std::string id;

        /// Header text when no selectable options are provided.
        std::string label;

        /// Optional column dropdown choices, with unique option IDs.
        ///
        /// The first option is selected by default.
        /// An absent or empty list uses `label` as a plain text header.
        std::optional<rerun::Collection<rerun::encodings::TableColumnOption>> column_dropdown;

        /// Render body cells as checkboxes instead of text when true.
        ///
        /// Defaults to false; checkbox data must contain only numeric zero or one.
        std::optional<bool> checkbox;

        /// Color numeric cell backgrounds by their magnitude and sign when true.
        ///
        /// Defaults to false and has no effect on text or checkbox cells.
        std::optional<bool> heatmap;

      public:
        TableColumnSchema() = default;
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::TableColumnSchema> {
        static constexpr std::string_view ComponentType = "rerun.encodings.TableColumnSchema";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::TableColumnSchema` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::TableColumnSchema* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const encodings::TableColumnSchema* elements,
            size_t num_elements
        );
    };
} // namespace rerun
