// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_column_option.def.rs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <string>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace rerun::encodings {
    /// **Encoding**: One dropdown option for a `archetypes::DataTable` column.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableColumnOption {
        /// Stable identity reported when this option is selected.
        std::string id;

        /// Text displayed in the header and its menu.
        std::string label;

      public:
        TableColumnOption() = default;
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::TableColumnOption> {
        static constexpr std::string_view ComponentType = "rerun.encodings.TableColumnOption";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::TableColumnOption` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::TableColumnOption* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const encodings::TableColumnOption* elements,
            size_t num_elements
        );
    };
} // namespace rerun
