// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_schema.def.rs".

#pragma once

#include "../collection.hpp"
#include "../result.hpp"
#include "table_group.hpp"
#include "table_sort_scope.hpp"

#include <cstdint>
#include <memory>
#include <optional>

namespace arrow {
    class Array;
    class DataType;
    class StructBuilder;
} // namespace arrow

namespace rerun::encodings {
    /// **Encoding**: The groups and display settings of a `archetypes::DataTable`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableSchema {
        /// Groups in display and data order.
        rerun::Collection<rerun::encodings::TableGroup> groups;

        /// Scope of header-click sorting; defaults to the whole table.
        std::optional<rerun::encodings::TableSortScope> sort_scope;

        /// Number of leading columns kept visible while scrolling; defaults to one.
        std::optional<uint32_t> sticky_columns;

        /// One-based summary rows that start visual row groups.
        ///
        /// For example, `[1, 10, 20]` creates groups `[1, 10)`, `[10, 20)`, and `[20, …)`.
        /// Groups are collapsed by default, leaving each summary row visible with a disclosure control.
        /// Sorting orders whole groups by their summary values and therefore uses table-wide scope.
        std::optional<rerun::Collection<uint64_t>> row_groups;

      public:
        TableSchema() = default;
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::TableSchema> {
        static constexpr std::string_view ComponentType = "rerun.encodings.TableSchema";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::TableSchema` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::TableSchema* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::StructBuilder* builder, const encodings::TableSchema* elements,
            size_t num_elements
        );
    };
} // namespace rerun
