// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_value.def.rs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <cstring>
#include <memory>
#include <new>
#include <string>
#include <utility>

namespace arrow {
    class Array;
    class DataType;
    class DenseUnionBuilder;
} // namespace arrow

namespace rerun::encodings {
    namespace detail {
        /// \private
        enum class TableValueTag : uint8_t {
            /// Having a special empty state makes it possible to implement move-semantics. We need to be able to leave the object in a state which we can run the destructor on.
            None = 0,
            Number,
            Text,
        };

        /// \private
        union TableValueData {
            /// A 64-bit floating-point number.
            double number;

            /// A UTF-8 text value.
            std::string text;

            TableValueData() {
                std::memset(reinterpret_cast<void*>(this), 0, sizeof(TableValueData));
            }

            ~TableValueData() {}

            void swap(TableValueData& other) noexcept {
                // This bitwise swap would fail for self-referential types, but we don't have any of those.
                char temp[sizeof(TableValueData)];
                void* otherbytes = reinterpret_cast<void*>(&other);
                void* thisbytes = reinterpret_cast<void*>(this);
                std::memcpy(temp, thisbytes, sizeof(TableValueData));
                std::memcpy(thisbytes, otherbytes, sizeof(TableValueData));
                std::memcpy(otherbytes, temp, sizeof(TableValueData));
            }
        };
    } // namespace detail

    /// **Encoding**: A number or text value, suitable for a cell in a mixed-type table row.
    ///
    /// Numbers use 64-bit floating point.
    /// For homogeneous numeric columns that retain their element type, use
    /// `encodings::TableBuffer` instead.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct TableValue {
        TableValue() : _tag(detail::TableValueTag::None) {}

        /// Copy constructor
        TableValue(const TableValue& other) : _tag(other._tag) {
            switch (other._tag) {
                case detail::TableValueTag::Text: {
                    using TypeAlias = std::string;
                    new (&_data.text) TypeAlias(other._data.text);
                } break;
                case detail::TableValueTag::Number: {
                    const void* otherbytes = reinterpret_cast<const void*>(&other._data);
                    void* thisbytes = reinterpret_cast<void*>(&this->_data);
                    std::memcpy(thisbytes, otherbytes, sizeof(detail::TableValueData));
                } break;
                case detail::TableValueTag::None: {
                } break;
                default:
                    assert(false && "unreachable");
            }
        }

        TableValue& operator=(const TableValue& other) noexcept {
            TableValue tmp(other);
            this->swap(tmp);
            return *this;
        }

        TableValue(TableValue&& other) noexcept : TableValue() {
            this->swap(other);
        }

        TableValue& operator=(TableValue&& other) noexcept {
            this->swap(other);
            return *this;
        }

        ~TableValue() {
            switch (this->_tag) {
                case detail::TableValueTag::None: {
                    // Nothing to destroy
                } break;
                case detail::TableValueTag::Number: {
                    // has a trivial destructor
                } break;
                case detail::TableValueTag::Text: {
                    using TypeAlias = std::string;
                    _data.text.~TypeAlias();
                } break;
                default:
                    assert(false && "unreachable");
            }
        }

        void swap(TableValue& other) noexcept {
            std::swap(this->_tag, other._tag);
            this->_data.swap(other._data);
        }

        /// A 64-bit floating-point number.
        TableValue(double number) : TableValue() {
            *this = TableValue::number(std::move(number));
        }

        /// A UTF-8 text value.
        TableValue(std::string text) : TableValue() {
            *this = TableValue::text(std::move(text));
        }

        /// A 64-bit floating-point number.
        static TableValue number(double number) {
            TableValue self;
            self._tag = detail::TableValueTag::Number;
            new (&self._data.number) double(std::move(number));
            return self;
        }

        /// A UTF-8 text value.
        static TableValue text(std::string text) {
            TableValue self;
            self._tag = detail::TableValueTag::Text;
            new (&self._data.text) std::string(std::move(text));
            return self;
        }

        /// Return a pointer to number if the union is in that state, otherwise `nullptr`.
        const double* get_number() const {
            if (_tag == detail::TableValueTag::Number) {
                return &_data.number;
            } else {
                return nullptr;
            }
        }

        /// Return a pointer to text if the union is in that state, otherwise `nullptr`.
        const std::string* get_text() const {
            if (_tag == detail::TableValueTag::Text) {
                return &_data.text;
            } else {
                return nullptr;
            }
        }

        /// \private
        const detail::TableValueData& get_union_data() const {
            return _data;
        }

        /// \private
        detail::TableValueTag get_union_tag() const {
            return _tag;
        }

      private:
        detail::TableValueTag _tag;
        detail::TableValueData _data;
    };
} // namespace rerun::encodings

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<encodings::TableValue> {
        static constexpr std::string_view ComponentType = "rerun.encodings.TableValue";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_data_type();

        /// Serializes an array of `rerun::encodings::TableValue` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const encodings::TableValue* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::DenseUnionBuilder* builder, const encodings::TableValue* elements,
            size_t num_elements
        );
    };
} // namespace rerun
