# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/table_schema.def.rs".

# You can extend this class by creating a "TableSchemaExt" class in "table_schema_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .._converters import (
    int_or_none,
    to_np_uint64,
)
from .table_schema_ext import TableSchemaExt

if TYPE_CHECKING:
    import numpy as np
    import numpy.typing as npt

    from .. import encodings

__all__ = ["TableSchema", "TableSchemaArrayLike", "TableSchemaBatch", "TableSchemaLike"]


@define(init=False)
class TableSchema(TableSchemaExt):
    """
    **Encoding**: The groups and display settings of a [`archetypes.DataTable`][rerun.archetypes.DataTable].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(
        self: Any,
        groups: encodings.TableGroupArrayLike,
        *,
        sort_scope: encodings.TableSortScopeLike | None = None,
        sticky_columns: int | None = None,
        row_groups: npt.ArrayLike | None = None,
    ) -> None:
        """
        Create a new instance of the TableSchema encoding.

        Parameters
        ----------
        groups:
            Groups in display and data order.
        sort_scope:
            Scope of header-click sorting; defaults to the whole table.
        sticky_columns:
            Number of leading columns kept visible while scrolling; defaults to one.
        row_groups:
            One-based summary rows that start visual row groups.

            For example, `[1, 10, 20]` creates groups `[1, 10)`, `[10, 20)`, and `[20, …)`.
            Groups are collapsed by default, leaving each summary row visible with a disclosure control.
            Sorting orders whole groups by their summary values and therefore uses table-wide scope.

        """

        # You can define your own __init__ function as a member of TableSchemaExt in table_schema_ext.py
        self.__attrs_init__(groups=groups, sort_scope=sort_scope, sticky_columns=sticky_columns, row_groups=row_groups)

    groups: list[encodings.TableGroup] = field()
    # Groups in display and data order.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    sort_scope: encodings.TableSortScope | None = field(
        default=None,
        converter=TableSchemaExt.sort_scope__field_converter_override,  # type: ignore[misc]
    )
    # Scope of header-click sorting; defaults to the whole table.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    sticky_columns: int | None = field(default=None, converter=int_or_none)
    # Number of leading columns kept visible while scrolling; defaults to one.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    row_groups: npt.NDArray[np.uint64] | None = field(default=None, converter=to_np_uint64)
    # One-based summary rows that start visual row groups.
    #
    # For example, `[1, 10, 20]` creates groups `[1, 10)`, `[10, 20)`, and `[20, …)`.
    # Groups are collapsed by default, leaving each summary row visible with a disclosure control.
    # Sorting orders whole groups by their summary values and therefore uses table-wide scope.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


TableSchemaLike = TableSchema
"""A type alias for any TableSchema-like object."""

TableSchemaArrayLike = TableSchema | Sequence[TableSchemaLike]
"""A type alias for any TableSchema-like array object."""


class TableSchemaBatch(BaseBatch[TableSchemaArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field(
            "groups",
            pa.list_(
                pa.field(
                    "item",
                    pa.struct([
                        pa.field("id", pa.utf8(), nullable=False, metadata={}),
                        pa.field("primary_group", pa.utf8(), nullable=False, metadata={}),
                        pa.field("sub_group", pa.utf8(), nullable=True, metadata={}),
                        pa.field(
                            "columns",
                            pa.list_(
                                pa.field(
                                    "item",
                                    pa.struct([
                                        pa.field("id", pa.utf8(), nullable=False, metadata={}),
                                        pa.field("label", pa.utf8(), nullable=False, metadata={}),
                                        pa.field(
                                            "column_dropdown",
                                            pa.list_(
                                                pa.field(
                                                    "item",
                                                    pa.struct([
                                                        pa.field("id", pa.utf8(), nullable=False, metadata={}),
                                                        pa.field("label", pa.utf8(), nullable=False, metadata={}),
                                                    ]),
                                                    nullable=False,
                                                    metadata={},
                                                )
                                            ),
                                            nullable=True,
                                            metadata={},
                                        ),
                                        pa.field("checkbox", pa.bool_(), nullable=True, metadata={}),
                                        pa.field("heatmap", pa.bool_(), nullable=True, metadata={}),
                                    ]),
                                    nullable=False,
                                    metadata={},
                                )
                            ),
                            nullable=False,
                            metadata={},
                        ),
                    ]),
                    nullable=False,
                    metadata={},
                )
            ),
            nullable=False,
            metadata={},
        ),
        pa.field("sort_scope", pa.uint8(), nullable=True, metadata={}),
        pa.field("sticky_columns", pa.uint32(), nullable=True, metadata={}),
        pa.field(
            "row_groups",
            pa.list_(pa.field("item", pa.uint64(), nullable=False, metadata={})),
            nullable=True,
            metadata={},
        ),
    ])

    @staticmethod
    def _native_to_pa_array(data: TableSchemaArrayLike, data_type: pa.DataType) -> pa.Array:
        return TableSchemaExt.native_to_pa_array_override(data, data_type)
