# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/table_value.def.rs".

# You can extend this class by creating a "TableValueExt" class in "table_value_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .table_value_ext import TableValueExt

__all__ = ["TableValue", "TableValueArrayLike", "TableValueBatch", "TableValueLike"]


@define
class TableValue(TableValueExt):
    """
    **Encoding**: A number or text value, suitable for a cell in a mixed-type table row.

    Numbers use 64-bit floating point.
    For homogeneous numeric columns that retain their element type, use
    [`encodings.TableBuffer`][rerun.encodings.TableBuffer] instead.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    # You can define your own __init__ function as a member of TableValueExt in table_value_ext.py

    inner: float | str = field(
        converter=TableValueExt.inner__field_converter_override  # type: ignore[misc]
    )
    """
    Must be one of:

    * Number (float):
        A 64-bit floating-point number.

    * Text (str):
        A UTF-8 text value.
    """


if TYPE_CHECKING:
    from collections.abc import Sequence

    TableValueLike = TableValue | float | str
    """A type alias for any TableValue-like object."""

    TableValueArrayLike = TableValue | float | str | Sequence[TableValueLike]
    """A type alias for any TableValue-like array object."""
else:
    TableValueLike = Any
    TableValueArrayLike = Any


class TableValueBatch(BaseBatch[TableValueArrayLike]):
    _ARROW_DATATYPE = pa.dense_union([
        pa.field("_null_markers", pa.null(), nullable=True, metadata={}),
        pa.field("Number", pa.float64(), nullable=False, metadata={}),
        pa.field("Text", pa.utf8(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: TableValueArrayLike, data_type: pa.DataType) -> pa.Array:

        from typing import cast

        if not hasattr(data, "__iter__") or isinstance(data, (TableValue, float, str)):  # type: ignore[arg-type]
            data = [data]  # type: ignore[list-item]
        data = cast("Sequence[TableValueLike]", data)  # type: ignore[redundant-cast]

        types: list[int] = []
        value_offsets: list[int] = []

        num_nulls = 0
        variant_number: list[float] = []
        variant_text: list[str] = []

        for value in data:
            if value is None:
                value_offsets.append(num_nulls)
                num_nulls += 1
                types.append(0)
            else:
                if not isinstance(value, TableValue):
                    value = TableValue(value)
                if isinstance(value.inner, float):
                    value_offsets.append(len(variant_number))
                    variant_number.append(value.inner)
                    types.append(1)
                elif isinstance(value.inner, str):
                    value_offsets.append(len(variant_text))
                    variant_text.append(value.inner)
                    types.append(2)

        buffers = [
            None,
            pa.array(types, type=pa.int8()).buffers()[1],
            pa.array(value_offsets, type=pa.int32()).buffers()[1],
        ]
        children = [
            pa.nulls(num_nulls),
            pa.array(variant_number, type=pa.float64()),
            pa.array(variant_text, type=pa.utf8()),
        ]

        return pa.UnionArray.from_buffers(
            type=data_type,
            length=len(data),
            buffers=buffers,
            children=children,
        )
