# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/table_group.def.rs".

# You can extend this class by creating a "TableGroupExt" class in "table_group_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .._converters import (
    str_or_none,
)
from .table_group_ext import TableGroupExt

if TYPE_CHECKING:
    from .. import encodings

__all__ = ["TableGroup", "TableGroupArrayLike", "TableGroupBatch", "TableGroupLike"]


@define(init=False)
class TableGroup(TableGroupExt):
    """
    **Encoding**: A group of adjacent columns in a [`archetypes.DataTable`][rerun.archetypes.DataTable].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(
        self: Any,
        *,
        id: str,
        primary_group: str,
        columns: encodings.TableColumnSchemaArrayLike,
        sub_group: str | None = None,
    ) -> None:
        """
        Create a new instance of the TableGroup encoding.

        Parameters
        ----------
        id:
            Stable identity for this group, independent of its labels.
        primary_group:
            Primary group header text.
        sub_group:
            Optional subgroup header text.
        columns:
            Columns in display and data order.

        """

        # You can define your own __init__ function as a member of TableGroupExt in table_group_ext.py
        self.__attrs_init__(id=id, primary_group=primary_group, sub_group=sub_group, columns=columns)

    id: str = field(converter=str)
    # Stable identity for this group, independent of its labels.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    primary_group: str = field(converter=str)
    # Primary group header text.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    columns: list[encodings.TableColumnSchema] = field()
    # Columns in display and data order.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    sub_group: str | None = field(default=None, converter=str_or_none)
    # Optional subgroup header text.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


TableGroupLike = TableGroup
"""A type alias for any TableGroup-like object."""

TableGroupArrayLike = TableGroup | Sequence[TableGroupLike]
"""A type alias for any TableGroup-like array object."""


class TableGroupBatch(BaseBatch[TableGroupArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("id", pa.utf8(), nullable=False, metadata={}),
        pa.field("primary_group", pa.utf8(), nullable=False, metadata={}),
        pa.field("sub_group", pa.utf8(), nullable=True, metadata={}),
        pa.field(
            "columns",
            pa.list_(
                pa.field(
                    "item",
                    pa.struct([
                        pa.field("id", pa.utf8(), nullable=False, metadata={}),
                        pa.field("label", pa.utf8(), nullable=False, metadata={}),
                        pa.field(
                            "column_dropdown",
                            pa.list_(
                                pa.field(
                                    "item",
                                    pa.struct([
                                        pa.field("id", pa.utf8(), nullable=False, metadata={}),
                                        pa.field("label", pa.utf8(), nullable=False, metadata={}),
                                    ]),
                                    nullable=False,
                                    metadata={},
                                )
                            ),
                            nullable=True,
                            metadata={},
                        ),
                        pa.field("checkbox", pa.bool_(), nullable=True, metadata={}),
                        pa.field("heatmap", pa.bool_(), nullable=True, metadata={}),
                    ]),
                    nullable=False,
                    metadata={},
                )
            ),
            nullable=False,
            metadata={},
        ),
    ])

    @staticmethod
    def _native_to_pa_array(data: TableGroupArrayLike, data_type: pa.DataType) -> pa.Array:
        return TableGroupExt.native_to_pa_array_override(data, data_type)
