# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/table_column_schema.def.rs".

# You can extend this class by creating a "TableColumnSchemaExt" class in "table_column_schema_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .._converters import (
    bool_or_none,
)
from .table_column_schema_ext import TableColumnSchemaExt

if TYPE_CHECKING:
    from .. import encodings

__all__ = ["TableColumnSchema", "TableColumnSchemaArrayLike", "TableColumnSchemaBatch", "TableColumnSchemaLike"]


@define(init=False)
class TableColumnSchema(TableColumnSchemaExt):
    """
    **Encoding**: Header and presentation metadata for one [`archetypes.DataTable`][rerun.archetypes.DataTable] column.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(
        self: Any,
        id: str,
        label: str,
        *,
        column_dropdown: encodings.TableColumnOptionArrayLike | None = None,
        checkbox: bool | None = None,
        heatmap: bool | None = None,
    ) -> None:
        """
        Create a new instance of the TableColumnSchema encoding.

        Parameters
        ----------
        id:
            Stable identity within the group, independent of the displayed header.
        label:
            Header text when no selectable options are provided.
        column_dropdown:
            Optional column dropdown choices, with unique option IDs.

            The first option is selected by default.
            An absent or empty list uses `label` as a plain text header.
        checkbox:
            Render body cells as checkboxes instead of text when true.

            Defaults to false; checkbox data must contain only numeric zero or one.
        heatmap:
            Color numeric cell backgrounds by their magnitude and sign when true.

            Defaults to false and has no effect on text or checkbox cells.

        """

        # You can define your own __init__ function as a member of TableColumnSchemaExt in table_column_schema_ext.py
        self.__attrs_init__(id=id, label=label, column_dropdown=column_dropdown, checkbox=checkbox, heatmap=heatmap)

    id: str = field(converter=str)
    # Stable identity within the group, independent of the displayed header.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    label: str = field(converter=str)
    # Header text when no selectable options are provided.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    column_dropdown: list[encodings.TableColumnOption] | None = field(default=None)
    # Optional column dropdown choices, with unique option IDs.
    #
    # The first option is selected by default.
    # An absent or empty list uses `label` as a plain text header.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    checkbox: bool | None = field(default=None, converter=bool_or_none)
    # Render body cells as checkboxes instead of text when true.
    #
    # Defaults to false; checkbox data must contain only numeric zero or one.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    heatmap: bool | None = field(default=None, converter=bool_or_none)
    # Color numeric cell backgrounds by their magnitude and sign when true.
    #
    # Defaults to false and has no effect on text or checkbox cells.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


TableColumnSchemaLike = TableColumnSchema
"""A type alias for any TableColumnSchema-like object."""

TableColumnSchemaArrayLike = TableColumnSchema | Sequence[TableColumnSchemaLike]
"""A type alias for any TableColumnSchema-like array object."""


class TableColumnSchemaBatch(BaseBatch[TableColumnSchemaArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("id", pa.utf8(), nullable=False, metadata={}),
        pa.field("label", pa.utf8(), nullable=False, metadata={}),
        pa.field(
            "column_dropdown",
            pa.list_(
                pa.field(
                    "item",
                    pa.struct([
                        pa.field("id", pa.utf8(), nullable=False, metadata={}),
                        pa.field("label", pa.utf8(), nullable=False, metadata={}),
                    ]),
                    nullable=False,
                    metadata={},
                )
            ),
            nullable=True,
            metadata={},
        ),
        pa.field("checkbox", pa.bool_(), nullable=True, metadata={}),
        pa.field("heatmap", pa.bool_(), nullable=True, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: TableColumnSchemaArrayLike, data_type: pa.DataType) -> pa.Array:
        return TableColumnSchemaExt.native_to_pa_array_override(data, data_type)
