# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/table_buffer.def.rs".

# You can extend this class by creating a "TableBufferExt" class in "table_buffer_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .table_buffer_ext import TableBufferExt

__all__ = ["TableBuffer", "TableBufferArrayLike", "TableBufferBatch", "TableBufferLike"]


@define
class TableBuffer(TableBufferExt):
    """
    **Encoding**: A numeric tensor or an array of text values for table data.

    The numeric variant preserves its shape and numeric element type without
    wrapping each element in a [`encodings.TableValue`][rerun.encodings.TableValue].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    # You can define your own __init__ function as a member of TableBufferExt in table_buffer_ext.py

    inner: encodings.TensorData | list[str] = field(
        converter=TableBufferExt.inner__field_converter_override  # type: ignore[misc]
    )
    """
    Must be one of:

    * Numeric (encodings.TensorData):
        Numeric values with a shape and a typed buffer.

    * Text (list[str]):
        A one-dimensional array of UTF-8 text values.
    """


if TYPE_CHECKING:
    from collections.abc import Sequence

    from .. import encodings

    TableBufferLike = TableBuffer | encodings.TensorData | list[str]
    """A type alias for any TableBuffer-like object."""

    TableBufferArrayLike = TableBuffer | encodings.TensorData | list[str] | Sequence[TableBufferLike]
    """A type alias for any TableBuffer-like array object."""
else:
    TableBufferLike = Any
    TableBufferArrayLike = Any


class TableBufferBatch(BaseBatch[TableBufferArrayLike]):
    _ARROW_DATATYPE = pa.dense_union([
        pa.field("_null_markers", pa.null(), nullable=True, metadata={}),
        pa.field(
            "Numeric",
            pa.struct([
                pa.field(
                    "shape",
                    pa.list_(pa.field("item", pa.uint64(), nullable=False, metadata={})),
                    nullable=False,
                    metadata={},
                ),
                pa.field(
                    "names",
                    pa.list_(pa.field("item", pa.utf8(), nullable=False, metadata={})),
                    nullable=True,
                    metadata={},
                ),
                pa.field(
                    "buffer",
                    pa.dense_union([
                        pa.field("_null_markers", pa.null(), nullable=True, metadata={}),
                        pa.field(
                            "U8",
                            pa.list_(pa.field("item", pa.uint8(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "U16",
                            pa.list_(pa.field("item", pa.uint16(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "U32",
                            pa.list_(pa.field("item", pa.uint32(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "U64",
                            pa.list_(pa.field("item", pa.uint64(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "I8",
                            pa.list_(pa.field("item", pa.int8(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "I16",
                            pa.list_(pa.field("item", pa.int16(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "I32",
                            pa.list_(pa.field("item", pa.int32(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "I64",
                            pa.list_(pa.field("item", pa.int64(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "F16",
                            pa.list_(pa.field("item", pa.float16(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "F32",
                            pa.list_(pa.field("item", pa.float32(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                        pa.field(
                            "F64",
                            pa.list_(pa.field("item", pa.float64(), nullable=False, metadata={})),
                            nullable=False,
                            metadata={},
                        ),
                    ]),
                    nullable=True,
                    metadata={},
                ),
            ]),
            nullable=False,
            metadata={},
        ),
        pa.field(
            "Text", pa.list_(pa.field("item", pa.utf8(), nullable=False, metadata={})), nullable=False, metadata={}
        ),
    ])

    @staticmethod
    def _native_to_pa_array(data: TableBufferArrayLike, data_type: pa.DataType) -> pa.Array:
        return TableBufferExt.native_to_pa_array_override(data, data_type)
