# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/table_column_option.def.rs".

# You can extend this class by creating a "TableColumnOptionExt" class in "table_column_option_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .table_column_option_ext import TableColumnOptionExt

__all__ = ["TableColumnOption", "TableColumnOptionArrayLike", "TableColumnOptionBatch", "TableColumnOptionLike"]


@define(init=False)
class TableColumnOption(TableColumnOptionExt):
    """
    **Encoding**: One dropdown option for a [`archetypes.DataTable`][rerun.archetypes.DataTable] column.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(self: Any, id: str, label: str) -> None:
        """
        Create a new instance of the TableColumnOption encoding.

        Parameters
        ----------
        id:
            Stable identity reported when this option is selected.
        label:
            Text displayed in the header and its menu.

        """

        # You can define your own __init__ function as a member of TableColumnOptionExt in table_column_option_ext.py
        self.__attrs_init__(id=id, label=label)

    id: str = field(converter=str)
    # Stable identity reported when this option is selected.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    label: str = field(converter=str)
    # Text displayed in the header and its menu.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


TableColumnOptionLike = TableColumnOption
"""A type alias for any TableColumnOption-like object."""

TableColumnOptionArrayLike = TableColumnOption | Sequence[TableColumnOptionLike]
"""A type alias for any TableColumnOption-like array object."""


class TableColumnOptionBatch(BaseBatch[TableColumnOptionArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("id", pa.utf8(), nullable=False, metadata={}),
        pa.field("label", pa.utf8(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: TableColumnOptionArrayLike, data_type: pa.DataType) -> pa.Array:
        return TableColumnOptionExt.native_to_pa_array_override(data, data_type)
