# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/encodings/table_sort_scope.def.rs".

# You can extend this class by creating a "TableSortScopeExt" class in "table_sort_scope_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

import pyarrow as pa

from .._baseclasses import (
    BaseBatch,
)

__all__ = ["TableSortScope", "TableSortScopeArrayLike", "TableSortScopeBatch", "TableSortScopeLike"]


from enum import Enum


class TableSortScope(Enum):
    """
    **Encoding**: How sorting reorders rows in a [`archetypes.DataTable`][rerun.archetypes.DataTable].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    Table = 1
    """Sort all columns together."""

    Subgroup = 2
    """Sort each schema group independently."""

    @classmethod
    def auto(cls, val: str | int | TableSortScope) -> TableSortScope:
        """Best-effort converter, including a case-insensitive string matcher."""
        if isinstance(val, TableSortScope):
            return val
        if isinstance(val, int):
            return cls(val)
        try:
            return cls[val]
        except KeyError:
            val_lower = val.lower()
            for variant in cls:
                if variant.name.lower() == val_lower:
                    return variant
        raise ValueError(f"Cannot convert {val} to {cls.__name__}")

    def __str__(self) -> str:
        """Returns the variant name."""
        return self.name


TableSortScopeLike = TableSortScope | Literal["Subgroup", "Table", "subgroup", "table"] | int
"""A type alias for any TableSortScope-like object."""

TableSortScopeArrayLike = (
    TableSortScope | Literal["Subgroup", "Table", "subgroup", "table"] | int | Sequence[TableSortScopeLike]
)
"""A type alias for any TableSortScope-like array object."""


class TableSortScopeBatch(BaseBatch[TableSortScopeArrayLike]):
    _ARROW_DATATYPE = pa.uint8()

    @staticmethod
    def _native_to_pa_array(data: TableSortScopeArrayLike, data_type: pa.DataType) -> pa.Array:
        if isinstance(data, (TableSortScope, int, str)):
            data = [data]

        pa_data = [TableSortScope.auto(v).value if v is not None else None for v in data]  # type: ignore[redundant-expr]  # ty: ignore[not-iterable]

        return pa.array(pa_data, type=data_type)
