// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/archetypes/datatable.def.rs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/table_column.hpp"
#include "../components/table_row.hpp"
#include "../components/table_schema.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: A grouped table with row-major or column-major data.
    ///
    /// Displayed by the DataTable view.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct DataTable {
        /// Row-major data, with one cell per schema column in each row.
        std::optional<ComponentBatch> rows;

        /// Column-major data, with one buffer per schema column.
        ///
        /// Column lengths may differ; the view uses the longest column as its display height and leaves missing cells blank.
        /// Numeric buffers must be one-dimensional tensors.
        std::optional<ComponentBatch> cols;

        /// Group and column definitions for either data layout.
        std::optional<ComponentBatch> schema;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.DataTable";

        /// `ComponentDescriptor` for the `rows` field.
        static constexpr auto Descriptor_rows = ComponentDescriptor(
            ArchetypeName, "DataTable:rows", Loggable<rerun::components::TableRow>::ComponentType
        );
        /// `ComponentDescriptor` for the `cols` field.
        static constexpr auto Descriptor_cols = ComponentDescriptor(
            ArchetypeName, "DataTable:cols", Loggable<rerun::components::TableColumn>::ComponentType
        );
        /// `ComponentDescriptor` for the `schema` field.
        static constexpr auto Descriptor_schema = ComponentDescriptor(
            ArchetypeName, "DataTable:schema",
            Loggable<rerun::components::TableSchema>::ComponentType
        );

      public:
        DataTable() = default;
        DataTable(DataTable&& other) = default;
        DataTable(const DataTable& other) = default;
        DataTable& operator=(const DataTable& other) = default;
        DataTable& operator=(DataTable&& other) = default;

        explicit DataTable(rerun::components::TableSchema _schema)
            : schema(ComponentBatch::from_loggable(std::move(_schema), Descriptor_schema)
                         .value_or_throw()) {}

        /// Update only some specific fields of a `DataTable`.
        static DataTable update_fields() {
            return DataTable();
        }

        /// Clear all the fields of a `DataTable`.
        static DataTable clear_fields();

        /// Row-major data, with one cell per schema column in each row.
        DataTable with_rows(const Collection<rerun::components::TableRow>& _rows) && {
            rows = ComponentBatch::from_loggable(_rows, Descriptor_rows).value_or_throw();
            return std::move(*this);
        }

        /// Column-major data, with one buffer per schema column.
        ///
        /// Column lengths may differ; the view uses the longest column as its display height and leaves missing cells blank.
        /// Numeric buffers must be one-dimensional tensors.
        DataTable with_cols(const Collection<rerun::components::TableColumn>& _cols) && {
            cols = ComponentBatch::from_loggable(_cols, Descriptor_cols).value_or_throw();
            return std::move(*this);
        }

        /// Group and column definitions for either data layout.
        DataTable with_schema(const rerun::components::TableSchema& _schema) && {
            schema = ComponentBatch::from_loggable(_schema, Descriptor_schema).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `schema` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_schema` should
        /// be used when logging a single row's worth of data.
        DataTable with_many_schema(const Collection<rerun::components::TableSchema>& _schema) && {
            schema = ComponentBatch::from_loggable(_schema, Descriptor_schema).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::DataTable> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(const archetypes::DataTable& archetype
        );
    };
} // namespace rerun
