// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/archetypes/datatable.def.rs".

#include "data_table.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    DataTable DataTable::clear_fields() {
        auto archetype = DataTable();
        archetype.rows =
            ComponentBatch::empty<rerun::components::TableRow>(Descriptor_rows).value_or_throw();
        archetype.cols =
            ComponentBatch::empty<rerun::components::TableColumn>(Descriptor_cols).value_or_throw();
        archetype.schema = ComponentBatch::empty<rerun::components::TableSchema>(Descriptor_schema)
                               .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> DataTable::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(3);
        if (rows.has_value()) {
            columns.push_back(rows.value().partitioned(lengths_).value_or_throw());
        }
        if (cols.has_value()) {
            columns.push_back(cols.value().partitioned(lengths_).value_or_throw());
        }
        if (schema.has_value()) {
            columns.push_back(schema.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> DataTable::columns() {
        if (rows.has_value()) {
            return columns(std::vector<uint32_t>(rows.value().length(), 1));
        }
        if (cols.has_value()) {
            return columns(std::vector<uint32_t>(cols.value().length(), 1));
        }
        if (schema.has_value()) {
            return columns(std::vector<uint32_t>(schema.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::DataTable>::as_batches(
        const archetypes::DataTable& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(3);

        if (archetype.rows.has_value()) {
            cells.push_back(archetype.rows.value());
        }
        if (archetype.cols.has_value()) {
            cells.push_back(archetype.cols.value());
        }
        if (archetype.schema.has_value()) {
            cells.push_back(archetype.schema.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
