# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/components/table_row.def.rs".

# You can extend this class by creating a "TableRowExt" class in "table_row_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
    ComponentBatchMixin,
    ComponentMixin,
)
from .table_row_ext import TableRowExt

if TYPE_CHECKING:
    from .. import encodings

__all__ = ["TableRow", "TableRowArrayLike", "TableRowBatch", "TableRowLike"]


@define(init=False)
class TableRow(TableRowExt, ComponentMixin):
    """
    **Component**: One row of a [`archetypes.DataTable`][rerun.archetypes.DataTable], in schema column order.

    Checkbox cells use `Number(0.0)` for unchecked and `Number(1.0)` for checked.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None

    def __init__(self: Any, values: TableRowLike) -> None:
        """Create a new instance of the TableRow component."""

        # You can define your own __init__ function as a member of TableRowExt in table_row_ext.py
        self.__attrs_init__(values=values)

    values: list[encodings.TableValue] = field()

    def __len__(self) -> int:
        # You can define your own __len__ function as a member of TableRowExt in table_row_ext.py
        return len(self.values)


TableRowLike = TableRow
"""A type alias for any TableRow-like object."""

TableRowArrayLike = TableRow | Sequence[TableRowLike]
"""A type alias for any TableRow-like array object."""


class TableRowBatch(BaseBatch[TableRowArrayLike], ComponentBatchMixin):
    _ARROW_DATATYPE = pa.list_(
        pa.field(
            "item",
            pa.dense_union([
                pa.field("_null_markers", pa.null(), nullable=True, metadata={}),
                pa.field("Number", pa.float64(), nullable=False, metadata={}),
                pa.field("Text", pa.utf8(), nullable=False, metadata={}),
            ]),
            nullable=True,
            metadata={},
        )
    )
    _COMPONENT_TYPE: str = "rerun.components.TableRow"

    @staticmethod
    def _native_to_pa_array(data: TableRowArrayLike, data_type: pa.DataType) -> pa.Array:
        return TableRowExt.native_to_pa_array_override(data, data_type)


# This is patched in late to avoid circular dependencies.
TableRow._BATCH_TYPE = TableRowBatch  # type: ignore[assignment]
