# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/components/table_schema.def.rs".

# You can extend this class by creating a "TableSchemaExt" class in "table_schema_ext.py".

from __future__ import annotations

from .. import encodings
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["TableSchema", "TableSchemaBatch"]


class TableSchema(encodings.TableSchema, ComponentMixin):
    """
    **Component**: The ordered groups and columns of a [`archetypes.DataTable`][rerun.archetypes.DataTable].

    Group IDs must be unique within the table, and column IDs must be unique within their group.
    Metadata and values are independent components; log compatible schema and data together when changing the structure.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of TableSchemaExt in table_schema_ext.py

    # Note: there are no fields here because TableSchema delegates to encodings.TableSchema


class TableSchemaBatch(encodings.TableSchemaBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.TableSchema"


# This is patched in late to avoid circular dependencies.
TableSchema._BATCH_TYPE = TableSchemaBatch  # type: ignore[assignment]
