# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/components/table_column.def.rs".

# You can extend this class by creating a "TableColumnExt" class in "table_column_ext.py".

from __future__ import annotations

from .. import encodings
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["TableColumn", "TableColumnBatch"]


class TableColumn(encodings.TableBuffer, ComponentMixin):
    """
    **Component**: One column of a [`archetypes.DataTable`][rerun.archetypes.DataTable].

    Numeric data must be a one-dimensional tensor.
    Checkbox columns use numeric zero for unchecked and one for checked.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of TableColumnExt in table_column_ext.py

    # Note: there are no fields here because TableColumn delegates to encodings.TableBuffer


class TableColumnBatch(encodings.TableBufferBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.TableColumn"


# This is patched in late to avoid circular dependencies.
TableColumn._BATCH_TYPE = TableColumnBatch  # type: ignore[assignment]
