# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/build/re_type_definitions/rerun/archetypes/datatable.def.rs".

# You can extend this class by creating a "DataTableExt" class in "data_table_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, encodings
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
    ComponentDescriptor,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.encodings import VisualizerComponentMappingLike

__all__ = ["DataTable"]


@define(str=False, repr=False, init=False)
class DataTable(Archetype, VisualizableArchetype):
    """
    **Archetype**: A grouped table with row-major or column-major data.

    Displayed by the DataTable view.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.archetypes.DataTable"

    def __init__(
        self: Any,
        schema: encodings.TableSchemaLike,
        *,
        rows: components.TableRowArrayLike | None = None,
        cols: encodings.TableBufferArrayLike | None = None,
    ) -> None:
        """
        Create a new instance of the DataTable archetype.

        Parameters
        ----------
        rows:
            Row-major data, with one cell per schema column in each row.
        cols:
            Column-major data, with one buffer per schema column.

            Column lengths may differ; the view uses the longest column as its display height and leaves missing cells blank.
            Numeric buffers must be one-dimensional tensors.
        schema:
            Group and column definitions for either data layout.

        """

        # You can define your own __init__ function as a member of DataTableExt in data_table_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(rows=rows, cols=cols, schema=schema)
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            rows=None,
            cols=None,
            schema=None,
        )

    @classmethod
    def _clear(cls) -> DataTable:
        """Produce an empty DataTable, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        rows: components.TableRowArrayLike | None = None,
        cols: encodings.TableBufferArrayLike | None = None,
        schema: encodings.TableSchemaLike | None = None,
    ) -> DataTable:
        """
        Update only some specific fields of a `DataTable`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        rows:
            Row-major data, with one cell per schema column in each row.
        cols:
            Column-major data, with one buffer per schema column.

            Column lengths may differ; the view uses the longest column as its display height and leaves missing cells blank.
            Numeric buffers must be one-dimensional tensors.
        schema:
            Group and column definitions for either data layout.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "rows": rows,
                "cols": cols,
                "schema": schema,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> DataTable:
        """Clear all the fields of a `DataTable`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_rows() -> ComponentDescriptor:
        return ComponentDescriptor(
            "DataTable:rows",
            archetype=DataTable.NAME,
            component_type=components.TableRowBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_cols() -> ComponentDescriptor:
        return ComponentDescriptor(
            "DataTable:cols",
            archetype=DataTable.NAME,
            component_type=components.TableColumnBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_schema() -> ComponentDescriptor:
        return ComponentDescriptor(
            "DataTable:schema",
            archetype=DataTable.NAME,
            component_type=components.TableSchemaBatch._COMPONENT_TYPE,
        )

    @classmethod
    def columns(
        cls,
        *,
        rows: components.TableRowArrayLike | None = None,
        cols: encodings.TableBufferArrayLike | None = None,
        schema: encodings.TableSchemaArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        rows:
            Row-major data, with one cell per schema column in each row.
        cols:
            Column-major data, with one buffer per schema column.

            Column lengths may differ; the view uses the longest column as its display height and leaves missing cells blank.
            Numeric buffers must be one-dimensional tensors.
        schema:
            Group and column definitions for either data layout.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                rows=rows,
                cols=cols,
                schema=schema,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {"DataTable:rows": rows, "DataTable:cols": cols, "DataTable:schema": schema}
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type):
                    elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                    if arrow_array.type.list_size == elem_flat_len:
                        # The product of the last dimensions of the shape are equal to the size of the fixed size list array,
                        # so we have `num_rows` single element batches (each element is a fixed sized list).
                        batch_length = 1
                    else:
                        batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]
                else:
                    # For primitive types, derive batch_length from the actual arrow array length
                    # since the input shape can be misleading (e.g. colors [R,G,B] -> single uint32).
                    batch_length = len(arrow_array) // num_rows if num_rows > 0 else 1

                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    schema: components.TableSchemaBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TableSchemaBatch._converter,  # type: ignore[misc]
    )
    # Group and column definitions for either data layout.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    rows: components.TableRowBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TableRowBatch._converter,  # type: ignore[misc]
    )
    # Row-major data, with one cell per schema column in each row.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    cols: components.TableColumnBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TableColumnBatch._converter,  # type: ignore[misc]
    )
    # Column-major data, with one buffer per schema column.
    #
    # Column lengths may differ; the view uses the longest column as its display height and leaves missing cells blank.
    # Numeric buffers must be one-dimensional tensors.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("DataTable", overrides=self.as_component_batches(), mappings=mappings)
