// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/archetypes/datatable.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Archetype**: A grouped table with row-major or column-major data.
///
/// Displayed by the DataTable view.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, Default, ::re_byte_size::SizeBytes)]
pub struct DataTable {
    /// Row-major data, with one cell per schema column in each row.
    pub rows: Option<SerializedComponentBatch>,

    /// Column-major data, with one buffer per schema column.
    ///
    /// Column lengths may differ; the view uses the longest column as its display height and leaves missing cells blank.
    /// Numeric buffers must be one-dimensional tensors.
    pub cols: Option<SerializedComponentBatch>,

    /// Group and column definitions for either data layout.
    pub schema: Option<SerializedComponentBatch>,
}

impl DataTable {
    /// Returns the [`ComponentDescriptor`] for [`Self::rows`].
    ///
    /// The corresponding component is [`crate::components::TableRow`].
    #[inline]
    pub fn descriptor_rows() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.DataTable".into()),
                component: "DataTable:rows".into(),
                component_type: Some("rerun.components.TableRow".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::cols`].
    ///
    /// The corresponding component is [`crate::components::TableColumn`].
    #[inline]
    pub fn descriptor_cols() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.DataTable".into()),
                component: "DataTable:cols".into(),
                component_type: Some("rerun.components.TableColumn".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::schema`].
    ///
    /// The corresponding component is [`crate::components::TableSchema`].
    #[inline]
    pub fn descriptor_schema() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.DataTable".into()),
                component: "DataTable:schema".into(),
                component_type: Some("rerun.components.TableSchema".into()),
            });
        (*DESCRIPTOR).clone()
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [DataTable::descriptor_schema()]);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| [DataTable::descriptor_rows(), DataTable::descriptor_cols()]);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            DataTable::descriptor_schema(),
            DataTable::descriptor_rows(),
            DataTable::descriptor_cols(),
        ]
    });

impl DataTable {
    /// The total number of components in the archetype: 1 required, 0 recommended, 2 optional
    pub const NUM_COMPONENTS: usize = 3usize;
}

impl ::re_types_core::Archetype for DataTable {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        ::re_types_core::external::re_string_interner::intern_static_nonempty!(
            ::re_types_core::ArchetypeName,
            "rerun.archetypes.DataTable"
        )
    }

    #[inline]
    fn display_name() -> &'static str {
        "Data table"
    }

    #[inline]
    fn required_components() -> Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{
            ArrowDataType as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
        };
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let rows = arrays_by_descr
            .get(&Self::descriptor_rows())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_rows()));
        let cols = arrays_by_descr
            .get(&Self::descriptor_cols())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_cols()));
        let schema = arrays_by_descr
            .get(&Self::descriptor_schema())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_schema()));
        Ok(Self { rows, cols, schema })
    }
}

impl ::re_types_core::AsComponents for DataTable {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [self.rows.clone(), self.cols.clone(), self.schema.clone()]
            .into_iter()
            .flatten()
            .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for DataTable {}

impl crate::VisualizableArchetype for DataTable {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("DataTable").with_overrides(self)
    }
}

impl DataTable {
    /// Create a new `DataTable`.
    #[inline]
    pub fn new(schema: impl Into<crate::components::TableSchema>) -> Self {
        Self {
            schema: try_serialize_field(Self::descriptor_schema(), [schema]),
            rows: None,
            cols: None,
        }
    }

    /// Update only some specific fields of a `DataTable`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `DataTable`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::ArrowDataType as _;
        Self {
            schema: Some(SerializedComponentBatch::new(
                crate::components::TableSchema::arrow_empty(),
                Self::descriptor_schema(),
            )),
            rows: Some(SerializedComponentBatch::new(
                crate::components::TableRow::arrow_empty(),
                Self::descriptor_rows(),
            )),
            cols: Some(SerializedComponentBatch::new(
                crate::components::TableColumn::arrow_empty(),
                Self::descriptor_cols(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.schema
                .map(|schema| schema.partitioned(_lengths.clone()))
                .transpose()?,
            self.rows
                .map(|rows| rows.partitioned(_lengths.clone()))
                .transpose()?,
            self.cols
                .map(|cols| cols.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_schema = self.schema.as_ref().map(|b| b.array.len());
        let len_rows = self.rows.as_ref().map(|b| b.array.len());
        let len_cols = self.cols.as_ref().map(|b| b.array.len());
        let len = None.or(len_schema).or(len_rows).or(len_cols).unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Group and column definitions for either data layout.
    #[inline]
    pub fn with_schema(mut self, schema: impl Into<crate::components::TableSchema>) -> Self {
        self.schema = try_serialize_field(Self::descriptor_schema(), [schema]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::TableSchema`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_schema`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_schema(
        mut self,
        schema: impl IntoIterator<Item = impl Into<crate::components::TableSchema>>,
    ) -> Self {
        self.schema = try_serialize_field(Self::descriptor_schema(), schema);
        self
    }

    /// Row-major data, with one cell per schema column in each row.
    #[inline]
    pub fn with_rows(
        mut self,
        rows: impl IntoIterator<Item = impl Into<crate::components::TableRow>>,
    ) -> Self {
        self.rows = try_serialize_field(Self::descriptor_rows(), rows);
        self
    }

    /// Column-major data, with one buffer per schema column.
    ///
    /// Column lengths may differ; the view uses the longest column as its display height and leaves missing cells blank.
    /// Numeric buffers must be one-dimensional tensors.
    #[inline]
    pub fn with_cols(
        mut self,
        cols: impl IntoIterator<Item = impl Into<crate::components::TableColumn>>,
    ) -> Self {
        self.cols = try_serialize_field(Self::descriptor_cols(), cols);
        self
    }
}
