// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_buffer.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Encoding**: A numeric tensor or an array of text values for table data.
///
/// The numeric variant preserves its shape and numeric element type without
/// wrapping each element in a [`encodings::TableValue`][crate::encodings::TableValue].
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, ::re_byte_size::SizeBytes)]
pub enum TableBuffer {
    /// Numeric values with a shape and a typed buffer.
    Numeric(crate::encodings::TensorData),

    /// A one-dimensional array of UTF-8 text values.
    Text(Vec<::re_types_core::ArrowString>),
}

::re_types_core::macros::impl_into_cow!(TableBuffer);

impl ::re_types_core::ArrowDataType for TableBuffer {
    #[inline]
    fn arrow_data_type() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Union(
            UnionFields::try_new(
                vec![0, 1, 2],
                vec![
                    Field::new("_null_markers", DataType::Null, true),
                    Field::new(
                        "Numeric",
                        <crate::encodings::TensorData>::arrow_data_type(),
                        false,
                    ),
                    Field::new(
                        "Text",
                        DataType::List(std::sync::Arc::new(Field::new(
                            "item",
                            DataType::Utf8,
                            false,
                        ))),
                        false,
                    ),
                ],
            )
            .expect("UnionFields::try_new should be infallible"),
            UnionMode::Dense,
        )
    }
}

impl ::re_types_core::ToArrowOpt for TableBuffer {
    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<Cow<'a, Self>>>>,
    ) -> SerializationResult<ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{
            ArrowDataType as _, ResultExt as _, ToArrow as _, ToArrowOpt as _,
            arrow_helpers::as_array_ref,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            // Dense Arrow union
            let data: Vec<_> = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<Cow<'a, Self>> = datum.map(Into::into);
                    datum
                })
                .collect();
            let field_type_ids = [0, 1, 2];
            let fields = vec![
                Field::new("_null_markers", DataType::Null, true),
                Field::new(
                    "Numeric",
                    <crate::encodings::TensorData>::arrow_data_type(),
                    false,
                ),
                Field::new(
                    "Text",
                    DataType::List(std::sync::Arc::new(Field::new(
                        "item",
                        DataType::Utf8,
                        false,
                    ))),
                    false,
                ),
            ];
            let type_ids: Vec<i8> = data
                .iter()
                .map(|a| match a.as_deref() {
                    None => 0,
                    Some(Self::Numeric(_)) => 1i8,
                    Some(Self::Text(_)) => 2i8,
                })
                .collect();
            let offsets = {
                let mut numeric_offset = 0;
                let mut text_offset = 0;
                let mut nulls_offset = 0;
                data.iter()
                    .map(|v| match v.as_deref() {
                        None => {
                            let offset = nulls_offset;
                            nulls_offset += 1;
                            offset
                        }
                        Some(Self::Numeric(_)) => {
                            let offset = numeric_offset;
                            numeric_offset += 1;
                            offset
                        }
                        Some(Self::Text(_)) => {
                            let offset = text_offset;
                            text_offset += 1;
                            offset
                        }
                    })
                    .collect()
            };
            let children = vec![
                as_array_ref(NullArray::new(data.iter().filter(|v| v.is_none()).count())),
                {
                    let numeric: Vec<_> = data
                        .iter()
                        .filter_map(|datum| match datum.as_deref() {
                            Some(Self::Numeric(v)) => Some(v.clone()),
                            _ => None,
                        })
                        .collect();
                    let numeric_validity = None;
                    {
                        let _: Option<arrow::buffer::NullBuffer> = numeric_validity;
                        crate::encodings::TensorData::to_arrow(numeric)?
                    }
                },
                {
                    let text: Vec<_> = data
                        .iter()
                        .filter_map(|datum| match datum.as_deref() {
                            Some(Self::Text(v)) => Some(v.clone()),
                            _ => None,
                        })
                        .collect();
                    let text_validity = None;
                    {
                        let offsets = arrow::buffer::OffsetBuffer::<i32>::from_lengths(
                            text.iter().map(|datum| datum.len()),
                        );
                        let text_inner_data: Vec<_> = text.into_iter().flatten().collect();
                        let text_inner_validity = None;
                        as_array_ref(ListArray::try_new(
                            std::sync::Arc::new(Field::new("item", DataType::Utf8, false)),
                            offsets,
                            {
                                let offsets = arrow::buffer::OffsetBuffer::from_lengths(
                                    text_inner_data.iter().map(|datum| datum.len()),
                                );
                                #[expect(clippy::unwrap_used)]
                                let capacity = offsets.last().copied().unwrap() as usize;
                                let mut buffer_builder =
                                    arrow::array::builder::BufferBuilder::<u8>::new(capacity);
                                for data in &text_inner_data {
                                    buffer_builder.append_slice(data.as_bytes());
                                }
                                let inner_data: arrow::buffer::Buffer = buffer_builder.finish();

                                #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                                as_array_ref(unsafe {
                                    StringArray::new_unchecked(
                                        offsets,
                                        inner_data,
                                        text_inner_validity,
                                    )
                                })
                            },
                            text_validity,
                        )?)
                    }
                },
            ];
            re_log::debug_assert_eq!(field_type_ids.len(), fields.len());
            re_log::debug_assert_eq!(fields.len(), children.len());
            as_array_ref(UnionArray::try_new(
                UnionFields::try_new(field_type_ids, fields)?,
                ScalarBuffer::from(type_ids),
                Some(offsets),
                children,
            )?)
        })
    }
}

::re_types_core::macros::impl_to_arrow_via_to_arrow_opt!(TableBuffer);

impl ::re_types_core::FromArrowOpt for TableBuffer {
    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>> {
        use ::re_types_core::{
            ArrowDataType as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
            arrow_helpers::*, arrow_zip_validity::ZipValidity,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let arrow_data = arrow_data
                .try_cast::<arrow::array::UnionArray>(|| Self::arrow_data_type())
                .with_context("rerun.encodings.TableBuffer")?;
            if arrow_data.is_empty() {
                Vec::new()
            } else {
                let arrow_data_type_ids = arrow_data.type_ids();
                let arrow_data_offsets = arrow_data
                    .offsets()
                    .ok_or_else(|| {
                        let expected = Self::arrow_data_type();
                        let actual = arrow_data.data_type().clone();
                        DeserializationError::datatype_mismatch(expected, actual)
                    })
                    .with_context("rerun.encodings.TableBuffer")?;
                if arrow_data_type_ids.len() != arrow_data_offsets.len() {
                    return Err(DeserializationError::offset_slice_oob(
                        (0, arrow_data_type_ids.len()),
                        arrow_data_offsets.len(),
                    ))
                    .with_context("rerun.encodings.TableBuffer");
                }
                let numeric = {
                    let arrow_data = arrow_data.child(1).as_ref();
                    crate::encodings::TensorData::from_arrow(arrow_data)
                        .with_context("rerun.encodings.TableBuffer#Numeric")?
                        .into_iter()
                        .map(Some)
                        .collect::<Vec<_>>()
                };
                let text = {
                    let arrow_data = arrow_data.child(2).as_ref();
                    {
                        let arrow_data = arrow_data
                            .try_cast::<arrow::array::ListArray>(|| {
                                DataType::List(std::sync::Arc::new(Field::new(
                                    "item",
                                    DataType::Utf8,
                                    false,
                                )))
                            })
                            .with_context("rerun.encodings.TableBuffer#Text")?;
                        if arrow_data.is_empty() {
                            Vec::new()
                        } else {
                            let arrow_data_inner = {
                                let arrow_data_inner = &**arrow_data.values();
                                {
                                    let arrow_data_inner = arrow_data_inner
                                        .try_cast::<StringArray>(|| DataType::Utf8)
                                        .with_context("rerun.encodings.TableBuffer#Text")?;
                                    let arrow_data_inner_buf = arrow_data_inner.values();
                                    let offsets = arrow_data_inner.offsets();
                                    ZipValidity::new_with_validity(
                                        offsets.array_windows(),
                                        arrow_data_inner.nulls(),
                                    )
                                    .map(|elem| {
                                        elem.map(|&[start, end]| {
                                            let start = start as usize;
                                            let end = end as usize;
                                            let len = end - start;
                                            if arrow_data_inner_buf.len() < end {
                                                return Err(
                                                    DeserializationError::offset_slice_oob(
                                                        (start, end),
                                                        arrow_data_inner_buf.len(),
                                                    ),
                                                );
                                            }
                                            let data =
                                                arrow_data_inner_buf.slice_with_length(start, len);
                                            Ok(data)
                                        })
                                        .transpose()
                                    })
                                    .map(|res_or_opt| {
                                        res_or_opt.map(|res_or_opt| {
                                            res_or_opt
                                                .map(|v| ::re_types_core::ArrowString::from(v))
                                        })
                                    })
                                    .collect::<DeserializationResult<Vec<Option<_>>>>()
                                    .with_context("rerun.encodings.TableBuffer#Text")?
                                    .into_iter()
                                }
                                .collect::<Vec<_>>()
                            };
                            let offsets = arrow_data.offsets();
                            ZipValidity::new_with_validity(
                                offsets.array_windows(),
                                arrow_data.nulls(),
                            )
                            .map(|elem| {
                                elem.map(|&[start, end]| {
                                    let start = start as usize;
                                    let end = end as usize;
                                    if arrow_data_inner.len() < end {
                                        return Err(DeserializationError::offset_slice_oob(
                                            (start, end),
                                            arrow_data_inner.len(),
                                        ));
                                    }

                                    #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                                    let data =
                                        unsafe { arrow_data_inner.get_unchecked(start..end) };
                                    let data = data
                                        .iter()
                                        .cloned()
                                        .map(Option::unwrap_or_default)
                                        .collect();
                                    Ok(data)
                                })
                                .transpose()
                            })
                            .collect::<DeserializationResult<Vec<Option<_>>>>()?
                        }
                        .into_iter()
                    }
                    .collect::<Vec<_>>()
                };
                arrow_data_type_ids
                    .iter()
                    .enumerate()
                    .map(|(i, typ)| {
                        let offset = arrow_data_offsets[i];
                        if *typ == 0 {
                            Ok(None)
                        } else {
                            Ok(Some(match typ {
                                1i8 => Self::Numeric({
                                    if offset as usize >= numeric.len() {
                                        return Err(DeserializationError::offset_oob(
                                            offset as _,
                                            numeric.len(),
                                        ))
                                        .with_context("rerun.encodings.TableBuffer#Numeric");
                                    }

                                    #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                                    unsafe { numeric.get_unchecked(offset as usize) }
                                        .clone()
                                        .ok_or_else(DeserializationError::missing_data)
                                        .with_context("rerun.encodings.TableBuffer#Numeric")?
                                }),
                                2i8 => Self::Text({
                                    if offset as usize >= text.len() {
                                        return Err(DeserializationError::offset_oob(
                                            offset as _,
                                            text.len(),
                                        ))
                                        .with_context("rerun.encodings.TableBuffer#Text");
                                    }

                                    #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                                    unsafe { text.get_unchecked(offset as usize) }
                                        .clone()
                                        .ok_or_else(DeserializationError::missing_data)
                                        .with_context("rerun.encodings.TableBuffer#Text")?
                                }),
                                _ => {
                                    return Err(DeserializationError::missing_union_arm(
                                        Self::arrow_data_type(),
                                        "<invalid>",
                                        *typ as _,
                                    ));
                                }
                            }))
                        }
                    })
                    .collect::<DeserializationResult<Vec<_>>>()
                    .with_context("rerun.encodings.TableBuffer")?
            }
        })
    }
}

::re_types_core::macros::impl_from_arrow_via_from_arrow_opt!(TableBuffer);
