// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_column_option.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Encoding**: One dropdown option for a [`archetypes::DataTable`][crate::archetypes::DataTable] column.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, PartialEq, Eq, ::re_byte_size::SizeBytes)]
pub struct TableColumnOption {
    /// Stable identity reported when this option is selected.
    pub id: ::re_types_core::ArrowString,

    /// Text displayed in the header and its menu.
    pub label: ::re_types_core::ArrowString,
}

::re_types_core::macros::impl_into_cow!(TableColumnOption);

impl ::re_types_core::ArrowDataType for TableColumnOption {
    #[inline]
    fn arrow_data_type() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Struct(Fields::from(vec![
            Field::new("id", DataType::Utf8, false),
            Field::new("label", DataType::Utf8, false),
        ]))
    }
}

impl ::re_types_core::ToArrow for TableColumnOption {
    fn to_arrow<'a>(
        data: impl IntoIterator<Item = impl Into<Cow<'a, Self>>>,
    ) -> SerializationResult<ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{
            ArrowDataType as _, ResultExt as _, ToArrow as _, ToArrowOpt as _,
            arrow_helpers::as_array_ref,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let fields = Fields::from(vec![
                Field::new("id", DataType::Utf8, false),
                Field::new("label", DataType::Utf8, false),
            ]);
            let data: Vec<_> = data
                .into_iter()
                .map(|datum| {
                    let datum: Cow<'a, Self> = datum.into();
                    datum
                })
                .collect();
            let validity = None;
            as_array_ref(StructArray::new(
                fields,
                vec![
                    {
                        let (somes, id): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.id.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let id_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let offsets =
                                arrow::buffer::OffsetBuffer::from_lengths(id.iter().map(|opt| {
                                    opt.as_ref().map(|datum| datum.len()).unwrap_or_default()
                                }));
                            #[expect(clippy::unwrap_used)]
                            let capacity = offsets.last().copied().unwrap() as usize;
                            let mut buffer_builder =
                                arrow::array::builder::BufferBuilder::<u8>::new(capacity);
                            for data in id.iter().flatten() {
                                buffer_builder.append_slice(data.as_bytes());
                            }
                            let inner_data: arrow::buffer::Buffer = buffer_builder.finish();

                            #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                            as_array_ref(unsafe {
                                StringArray::new_unchecked(offsets, inner_data, id_validity)
                            })
                        }
                    },
                    {
                        let (somes, label): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.label.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let label_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let offsets =
                                arrow::buffer::OffsetBuffer::from_lengths(label.iter().map(
                                    |opt| opt.as_ref().map(|datum| datum.len()).unwrap_or_default(),
                                ));

                            #[expect(clippy::unwrap_used)]
                            let capacity = offsets.last().copied().unwrap() as usize;
                            let mut buffer_builder =
                                arrow::array::builder::BufferBuilder::<u8>::new(capacity);
                            for data in label.iter().flatten() {
                                buffer_builder.append_slice(data.as_bytes());
                            }
                            let inner_data: arrow::buffer::Buffer = buffer_builder.finish();

                            #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                            as_array_ref(unsafe {
                                StringArray::new_unchecked(offsets, inner_data, label_validity)
                            })
                        }
                    },
                ],
                validity,
            ))
        })
    }
}

impl ::re_types_core::FromArrow for TableColumnOption {
    fn from_arrow(arrow_data: &dyn arrow::array::Array) -> DeserializationResult<Vec<Self>> {
        use ::re_types_core::{
            ArrowDataType as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
            arrow_helpers::*, arrow_zip_validity::ZipValidity,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        err_on_nulls(arrow_data, "rerun.encodings.TableColumnOption")?;
        Ok({
            {
                let arrow_data = arrow_data
                    .try_cast::<arrow::array::StructArray>(|| Self::arrow_data_type())
                    .with_context("rerun.encodings.TableColumnOption")?;
                if arrow_data.is_empty() {
                    Vec::new()
                } else {
                    let (arrow_data_fields, arrow_data_arrays) =
                        (arrow_data.fields(), arrow_data.columns());
                    let arrays_by_name: ::std::collections::HashMap<_, _> = ::std::iter::zip(
                        arrow_data_fields.iter().map(|field| field.name().as_str()),
                        arrow_data_arrays,
                    )
                    .collect();
                    let id = {
                        if !arrays_by_name.contains_key("id") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "id",
                            ))
                            .with_context("rerun.encodings.TableColumnOption");
                        }
                        let arrow_data = &**arrays_by_name["id"];
                        {
                            let arrow_data = arrow_data
                                .try_cast::<StringArray>(|| DataType::Utf8)
                                .with_context("rerun.encodings.TableColumnOption#id")?;
                            let arrow_data_buf = arrow_data.values();
                            let offsets = arrow_data.offsets();
                            ZipValidity::new_with_validity(
                                offsets.array_windows(),
                                arrow_data.nulls(),
                            )
                            .map(|elem| {
                                elem.map(|&[start, end]| {
                                    let start = start as usize;
                                    let end = end as usize;
                                    let len = end - start;
                                    if arrow_data_buf.len() < end {
                                        return Err(DeserializationError::offset_slice_oob(
                                            (start, end),
                                            arrow_data_buf.len(),
                                        ));
                                    }
                                    let data = arrow_data_buf.slice_with_length(start, len);
                                    Ok(data)
                                })
                                .transpose()
                            })
                            .map(|res_or_opt| {
                                res_or_opt.map(|res_or_opt| {
                                    res_or_opt.map(|v| ::re_types_core::ArrowString::from(v))
                                })
                            })
                            .collect::<DeserializationResult<Vec<Option<_>>>>()
                            .with_context("rerun.encodings.TableColumnOption#id")?
                            .into_iter()
                        }
                    };
                    let label = {
                        if !arrays_by_name.contains_key("label") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "label",
                            ))
                            .with_context("rerun.encodings.TableColumnOption");
                        }
                        let arrow_data = &**arrays_by_name["label"];
                        {
                            let arrow_data = arrow_data
                                .try_cast::<StringArray>(|| DataType::Utf8)
                                .with_context("rerun.encodings.TableColumnOption#label")?;
                            let arrow_data_buf = arrow_data.values();
                            let offsets = arrow_data.offsets();
                            ZipValidity::new_with_validity(
                                offsets.array_windows(),
                                arrow_data.nulls(),
                            )
                            .map(|elem| {
                                elem.map(|&[start, end]| {
                                    let start = start as usize;
                                    let end = end as usize;
                                    let len = end - start;
                                    if arrow_data_buf.len() < end {
                                        return Err(DeserializationError::offset_slice_oob(
                                            (start, end),
                                            arrow_data_buf.len(),
                                        ));
                                    }
                                    let data = arrow_data_buf.slice_with_length(start, len);
                                    Ok(data)
                                })
                                .transpose()
                            })
                            .map(|res_or_opt| {
                                res_or_opt.map(|res_or_opt| {
                                    res_or_opt.map(|v| ::re_types_core::ArrowString::from(v))
                                })
                            })
                            .collect::<DeserializationResult<Vec<Option<_>>>>()
                            .with_context("rerun.encodings.TableColumnOption#label")?
                            .into_iter()
                        }
                    };
                    ZipValidity::new_with_validity(
                        ::itertools::izip!(id, label),
                        arrow_data.nulls(),
                    )
                    .map(|opt| {
                        opt.map(|(id, label)| {
                            Ok(Self {
                                id: id
                                    .ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.encodings.TableColumnOption#id")?,
                                label: label
                                    .ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.encodings.TableColumnOption#label")?,
                            })
                        })
                        .transpose()
                    })
                    .collect::<DeserializationResult<Vec<_>>>()
                    .with_context("rerun.encodings.TableColumnOption")?
                }
            }
        }
        .into_iter()
        .map(|v| v.ok_or_else(DeserializationError::missing_data))
        .collect::<DeserializationResult<Vec<_>>>()?)
    }
}
