// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_value.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Encoding**: A number or text value, suitable for a cell in a mixed-type table row.
///
/// Numbers use 64-bit floating point.
/// For homogeneous numeric columns that retain their element type, use
/// [`encodings::TableBuffer`][crate::encodings::TableBuffer] instead.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, PartialEq, ::re_byte_size::SizeBytes)]
pub enum TableValue {
    /// A 64-bit floating-point number.
    Number(f64),

    /// A UTF-8 text value.
    Text(::re_types_core::ArrowString),
}

::re_types_core::macros::impl_into_cow!(TableValue);

impl ::re_types_core::ArrowDataType for TableValue {
    #[inline]
    fn arrow_data_type() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Union(
            UnionFields::try_new(
                vec![0, 1, 2],
                vec![
                    Field::new("_null_markers", DataType::Null, true),
                    Field::new("Number", DataType::Float64, false),
                    Field::new("Text", DataType::Utf8, false),
                ],
            )
            .expect("UnionFields::try_new should be infallible"),
            UnionMode::Dense,
        )
    }
}

impl ::re_types_core::ToArrowOpt for TableValue {
    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<Cow<'a, Self>>>>,
    ) -> SerializationResult<ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{
            ArrowDataType as _, ResultExt as _, ToArrow as _, ToArrowOpt as _,
            arrow_helpers::as_array_ref,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            // Dense Arrow union
            let data: Vec<_> = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<Cow<'a, Self>> = datum.map(Into::into);
                    datum
                })
                .collect();
            let field_type_ids = [0, 1, 2];
            let fields = vec![
                Field::new("_null_markers", DataType::Null, true),
                Field::new("Number", DataType::Float64, false),
                Field::new("Text", DataType::Utf8, false),
            ];
            let type_ids: Vec<i8> = data
                .iter()
                .map(|a| match a.as_deref() {
                    None => 0,
                    Some(Self::Number(_)) => 1i8,
                    Some(Self::Text(_)) => 2i8,
                })
                .collect();
            let offsets = {
                let mut number_offset = 0;
                let mut text_offset = 0;
                let mut nulls_offset = 0;
                data.iter()
                    .map(|v| match v.as_deref() {
                        None => {
                            let offset = nulls_offset;
                            nulls_offset += 1;
                            offset
                        }
                        Some(Self::Number(_)) => {
                            let offset = number_offset;
                            number_offset += 1;
                            offset
                        }
                        Some(Self::Text(_)) => {
                            let offset = text_offset;
                            text_offset += 1;
                            offset
                        }
                    })
                    .collect()
            };
            let children = vec![
                as_array_ref(NullArray::new(data.iter().filter(|v| v.is_none()).count())),
                {
                    let number: Vec<_> = data
                        .iter()
                        .filter_map(|datum| match datum.as_deref() {
                            Some(Self::Number(v)) => Some(v.clone()),
                            _ => None,
                        })
                        .collect();
                    let number_validity = None;
                    as_array_ref(PrimitiveArray::<Float64Type>::new(
                        number.into_iter().collect(),
                        number_validity,
                    ))
                },
                {
                    let text: Vec<_> = data
                        .iter()
                        .filter_map(|datum| match datum.as_deref() {
                            Some(Self::Text(v)) => Some(v.clone()),
                            _ => None,
                        })
                        .collect();
                    let text_validity = None;
                    {
                        let offsets = arrow::buffer::OffsetBuffer::from_lengths(
                            text.iter().map(|datum| datum.len()),
                        );
                        #[expect(clippy::unwrap_used)]
                        let capacity = offsets.last().copied().unwrap() as usize;
                        let mut buffer_builder =
                            arrow::array::builder::BufferBuilder::<u8>::new(capacity);
                        for data in &text {
                            buffer_builder.append_slice(data.as_bytes());
                        }
                        let inner_data: arrow::buffer::Buffer = buffer_builder.finish();

                        #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                        as_array_ref(unsafe {
                            StringArray::new_unchecked(offsets, inner_data, text_validity)
                        })
                    }
                },
            ];
            re_log::debug_assert_eq!(field_type_ids.len(), fields.len());
            re_log::debug_assert_eq!(fields.len(), children.len());
            as_array_ref(UnionArray::try_new(
                UnionFields::try_new(field_type_ids, fields)?,
                ScalarBuffer::from(type_ids),
                Some(offsets),
                children,
            )?)
        })
    }
}

::re_types_core::macros::impl_to_arrow_via_to_arrow_opt!(TableValue);

impl ::re_types_core::FromArrowOpt for TableValue {
    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>> {
        use ::re_types_core::{
            ArrowDataType as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
            arrow_helpers::*, arrow_zip_validity::ZipValidity,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let arrow_data = arrow_data
                .try_cast::<arrow::array::UnionArray>(|| Self::arrow_data_type())
                .with_context("rerun.encodings.TableValue")?;
            if arrow_data.is_empty() {
                Vec::new()
            } else {
                let arrow_data_type_ids = arrow_data.type_ids();
                let arrow_data_offsets = arrow_data
                    .offsets()
                    .ok_or_else(|| {
                        let expected = Self::arrow_data_type();
                        let actual = arrow_data.data_type().clone();
                        DeserializationError::datatype_mismatch(expected, actual)
                    })
                    .with_context("rerun.encodings.TableValue")?;
                if arrow_data_type_ids.len() != arrow_data_offsets.len() {
                    return Err(DeserializationError::offset_slice_oob(
                        (0, arrow_data_type_ids.len()),
                        arrow_data_offsets.len(),
                    ))
                    .with_context("rerun.encodings.TableValue");
                }
                let number = {
                    let arrow_data = arrow_data.child(1).as_ref();
                    arrow_data
                        .try_cast::<Float64Array>(|| DataType::Float64)
                        .with_context("rerun.encodings.TableValue#Number")?
                        .into_iter()
                        .collect::<Vec<_>>()
                };
                let text = {
                    let arrow_data = arrow_data.child(2).as_ref();
                    {
                        let arrow_data = arrow_data
                            .try_cast::<StringArray>(|| DataType::Utf8)
                            .with_context("rerun.encodings.TableValue#Text")?;
                        let arrow_data_buf = arrow_data.values();
                        let offsets = arrow_data.offsets();
                        ZipValidity::new_with_validity(offsets.array_windows(), arrow_data.nulls())
                            .map(|elem| {
                                elem.map(|&[start, end]| {
                                    let start = start as usize;
                                    let end = end as usize;
                                    let len = end - start;
                                    if arrow_data_buf.len() < end {
                                        return Err(DeserializationError::offset_slice_oob(
                                            (start, end),
                                            arrow_data_buf.len(),
                                        ));
                                    }
                                    let data = arrow_data_buf.slice_with_length(start, len);
                                    Ok(data)
                                })
                                .transpose()
                            })
                            .map(|res_or_opt| {
                                res_or_opt.map(|res_or_opt| {
                                    res_or_opt.map(|v| ::re_types_core::ArrowString::from(v))
                                })
                            })
                            .collect::<DeserializationResult<Vec<Option<_>>>>()
                            .with_context("rerun.encodings.TableValue#Text")?
                            .into_iter()
                    }
                    .collect::<Vec<_>>()
                };
                arrow_data_type_ids
                    .iter()
                    .enumerate()
                    .map(|(i, typ)| {
                        let offset = arrow_data_offsets[i];
                        if *typ == 0 {
                            Ok(None)
                        } else {
                            Ok(Some(match typ {
                                1i8 => Self::Number({
                                    if offset as usize >= number.len() {
                                        return Err(DeserializationError::offset_oob(
                                            offset as _,
                                            number.len(),
                                        ))
                                        .with_context("rerun.encodings.TableValue#Number");
                                    }

                                    #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                                    unsafe { number.get_unchecked(offset as usize) }
                                        .clone()
                                        .ok_or_else(DeserializationError::missing_data)
                                        .with_context("rerun.encodings.TableValue#Number")?
                                }),
                                2i8 => Self::Text({
                                    if offset as usize >= text.len() {
                                        return Err(DeserializationError::offset_oob(
                                            offset as _,
                                            text.len(),
                                        ))
                                        .with_context("rerun.encodings.TableValue#Text");
                                    }

                                    #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                                    unsafe { text.get_unchecked(offset as usize) }
                                        .clone()
                                        .ok_or_else(DeserializationError::missing_data)
                                        .with_context("rerun.encodings.TableValue#Text")?
                                }),
                                _ => {
                                    return Err(DeserializationError::missing_union_arm(
                                        Self::arrow_data_type(),
                                        "<invalid>",
                                        *typ as _,
                                    ));
                                }
                            }))
                        }
                    })
                    .collect::<DeserializationResult<Vec<_>>>()
                    .with_context("rerun.encodings.TableValue")?
            }
        })
    }
}

::re_types_core::macros::impl_from_arrow_via_from_arrow_opt!(TableValue);
