// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_group.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Encoding**: A group of adjacent columns in a [`archetypes::DataTable`][crate::archetypes::DataTable].
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, PartialEq, ::re_byte_size::SizeBytes)]
pub struct TableGroup {
    /// Stable identity for this group, independent of its labels.
    pub id: ::re_types_core::ArrowString,

    /// Primary group header text.
    pub primary_group: ::re_types_core::ArrowString,

    /// Optional subgroup header text.
    pub sub_group: Option<::re_types_core::ArrowString>,

    /// Columns in display and data order.
    pub columns: Vec<crate::encodings::TableColumnSchema>,
}

::re_types_core::macros::impl_into_cow!(TableGroup);

impl ::re_types_core::ArrowDataType for TableGroup {
    #[inline]
    fn arrow_data_type() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Struct(Fields::from(vec![
            Field::new("id", DataType::Utf8, false),
            Field::new("primary_group", DataType::Utf8, false),
            Field::new("sub_group", DataType::Utf8, true),
            Field::new(
                "columns",
                DataType::List(std::sync::Arc::new(Field::new(
                    "item",
                    <crate::encodings::TableColumnSchema>::arrow_data_type(),
                    false,
                ))),
                false,
            ),
        ]))
    }
}

impl ::re_types_core::ToArrow for TableGroup {
    fn to_arrow<'a>(
        data: impl IntoIterator<Item = impl Into<Cow<'a, Self>>>,
    ) -> SerializationResult<ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{
            ArrowDataType as _, ResultExt as _, ToArrow as _, ToArrowOpt as _,
            arrow_helpers::as_array_ref,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let fields = Fields::from(vec![
                Field::new("id", DataType::Utf8, false),
                Field::new("primary_group", DataType::Utf8, false),
                Field::new("sub_group", DataType::Utf8, true),
                Field::new(
                    "columns",
                    DataType::List(std::sync::Arc::new(Field::new(
                        "item",
                        <crate::encodings::TableColumnSchema>::arrow_data_type(),
                        false,
                    ))),
                    false,
                ),
            ]);
            let data: Vec<_> = data
                .into_iter()
                .map(|datum| {
                    let datum: Cow<'a, Self> = datum.into();
                    datum
                })
                .collect();
            let validity = None;
            as_array_ref(StructArray::new(
                fields,
                vec![
                    {
                        let (somes, id): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.id.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let id_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let offsets =
                                arrow::buffer::OffsetBuffer::from_lengths(id.iter().map(|opt| {
                                    opt.as_ref().map(|datum| datum.len()).unwrap_or_default()
                                }));
                            #[expect(clippy::unwrap_used)]
                            let capacity = offsets.last().copied().unwrap() as usize;
                            let mut buffer_builder =
                                arrow::array::builder::BufferBuilder::<u8>::new(capacity);
                            for data in id.iter().flatten() {
                                buffer_builder.append_slice(data.as_bytes());
                            }
                            let inner_data: arrow::buffer::Buffer = buffer_builder.finish();

                            #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                            as_array_ref(unsafe {
                                StringArray::new_unchecked(offsets, inner_data, id_validity)
                            })
                        }
                    },
                    {
                        let (somes, primary_group): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.primary_group.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let primary_group_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let offsets = arrow::buffer::OffsetBuffer::from_lengths(
                                primary_group.iter().map(|opt| {
                                    opt.as_ref().map(|datum| datum.len()).unwrap_or_default()
                                }),
                            );
                            #[expect(clippy::unwrap_used)]
                            let capacity = offsets.last().copied().unwrap() as usize;
                            let mut buffer_builder =
                                arrow::array::builder::BufferBuilder::<u8>::new(capacity);
                            for data in primary_group.iter().flatten() {
                                buffer_builder.append_slice(data.as_bytes());
                            }
                            let inner_data: arrow::buffer::Buffer = buffer_builder.finish();

                            #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                            as_array_ref(unsafe {
                                StringArray::new_unchecked(
                                    offsets,
                                    inner_data,
                                    primary_group_validity,
                                )
                            })
                        }
                    },
                    {
                        let (somes, sub_group): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.sub_group.clone()).flatten();
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let sub_group_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let offsets =
                                arrow::buffer::OffsetBuffer::from_lengths(sub_group.iter().map(
                                    |opt| opt.as_ref().map(|datum| datum.len()).unwrap_or_default(),
                                ));
                            #[expect(clippy::unwrap_used)]
                            let capacity = offsets.last().copied().unwrap() as usize;
                            let mut buffer_builder =
                                arrow::array::builder::BufferBuilder::<u8>::new(capacity);
                            for data in sub_group.iter().flatten() {
                                buffer_builder.append_slice(data.as_bytes());
                            }
                            let inner_data: arrow::buffer::Buffer = buffer_builder.finish();

                            #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                            as_array_ref(unsafe {
                                StringArray::new_unchecked(offsets, inner_data, sub_group_validity)
                            })
                        }
                    },
                    {
                        let (somes, columns): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.columns.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let columns_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let offsets = arrow::buffer::OffsetBuffer::<i32>::from_lengths(
                                columns
                                    .iter()
                                    .map(|opt| opt.as_ref().map_or(0, |datum| datum.len())),
                            );
                            let columns_inner_data: Vec<_> =
                                columns.into_iter().flatten().flatten().collect();
                            let columns_inner_validity = None;
                            as_array_ref(ListArray::try_new(
                                std::sync::Arc::new(Field::new(
                                    "item",
                                    <crate::encodings::TableColumnSchema>::arrow_data_type(),
                                    false,
                                )),
                                offsets,
                                {
                                    let _: Option<arrow::buffer::NullBuffer> =
                                        columns_inner_validity;
                                    crate::encodings::TableColumnSchema::to_arrow(
                                        columns_inner_data,
                                    )?
                                },
                                columns_validity,
                            )?)
                        }
                    },
                ],
                validity,
            ))
        })
    }
}

impl ::re_types_core::FromArrow for TableGroup {
    fn from_arrow(arrow_data: &dyn arrow::array::Array) -> DeserializationResult<Vec<Self>> {
        use ::re_types_core::{
            ArrowDataType as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
            arrow_helpers::*, arrow_zip_validity::ZipValidity,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        err_on_nulls(arrow_data, "rerun.encodings.TableGroup")?;
        Ok({
            {
                let arrow_data = arrow_data
                    .try_cast::<arrow::array::StructArray>(|| Self::arrow_data_type())
                    .with_context("rerun.encodings.TableGroup")?;
                if arrow_data.is_empty() {
                    Vec::new()
                } else {
                    let (arrow_data_fields, arrow_data_arrays) =
                        (arrow_data.fields(), arrow_data.columns());
                    let arrays_by_name: ::std::collections::HashMap<_, _> = ::std::iter::zip(
                        arrow_data_fields.iter().map(|field| field.name().as_str()),
                        arrow_data_arrays,
                    )
                    .collect();
                    let id = {
                        if !arrays_by_name.contains_key("id") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "id",
                            ))
                            .with_context("rerun.encodings.TableGroup");
                        }
                        let arrow_data = &**arrays_by_name["id"];
                        {
                            let arrow_data = arrow_data
                                .try_cast::<StringArray>(|| DataType::Utf8)
                                .with_context("rerun.encodings.TableGroup#id")?;
                            let arrow_data_buf = arrow_data.values();
                            let offsets = arrow_data.offsets();
                            ZipValidity::new_with_validity(
                                offsets.array_windows(),
                                arrow_data.nulls(),
                            )
                            .map(|elem| {
                                elem.map(|&[start, end]| {
                                    let start = start as usize;
                                    let end = end as usize;
                                    let len = end - start;
                                    if arrow_data_buf.len() < end {
                                        return Err(DeserializationError::offset_slice_oob(
                                            (start, end),
                                            arrow_data_buf.len(),
                                        ));
                                    }
                                    let data = arrow_data_buf.slice_with_length(start, len);
                                    Ok(data)
                                })
                                .transpose()
                            })
                            .map(|res_or_opt| {
                                res_or_opt.map(|res_or_opt| {
                                    res_or_opt.map(|v| ::re_types_core::ArrowString::from(v))
                                })
                            })
                            .collect::<DeserializationResult<Vec<Option<_>>>>()
                            .with_context("rerun.encodings.TableGroup#id")?
                            .into_iter()
                        }
                    };
                    let primary_group = {
                        if !arrays_by_name.contains_key("primary_group") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "primary_group",
                            ))
                            .with_context("rerun.encodings.TableGroup");
                        }
                        let arrow_data = &**arrays_by_name["primary_group"];
                        {
                            let arrow_data = arrow_data
                                .try_cast::<StringArray>(|| DataType::Utf8)
                                .with_context("rerun.encodings.TableGroup#primary_group")?;
                            let arrow_data_buf = arrow_data.values();
                            let offsets = arrow_data.offsets();
                            ZipValidity::new_with_validity(
                                offsets.array_windows(),
                                arrow_data.nulls(),
                            )
                            .map(|elem| {
                                elem.map(|&[start, end]| {
                                    let start = start as usize;
                                    let end = end as usize;
                                    let len = end - start;
                                    if arrow_data_buf.len() < end {
                                        return Err(DeserializationError::offset_slice_oob(
                                            (start, end),
                                            arrow_data_buf.len(),
                                        ));
                                    }
                                    let data = arrow_data_buf.slice_with_length(start, len);
                                    Ok(data)
                                })
                                .transpose()
                            })
                            .map(|res_or_opt| {
                                res_or_opt.map(|res_or_opt| {
                                    res_or_opt.map(|v| ::re_types_core::ArrowString::from(v))
                                })
                            })
                            .collect::<DeserializationResult<Vec<Option<_>>>>()
                            .with_context("rerun.encodings.TableGroup#primary_group")?
                            .into_iter()
                        }
                    };
                    let sub_group = {
                        if !arrays_by_name.contains_key("sub_group") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "sub_group",
                            ))
                            .with_context("rerun.encodings.TableGroup");
                        }
                        let arrow_data = &**arrays_by_name["sub_group"];
                        {
                            let arrow_data = arrow_data
                                .try_cast::<StringArray>(|| DataType::Utf8)
                                .with_context("rerun.encodings.TableGroup#sub_group")?;
                            let arrow_data_buf = arrow_data.values();
                            let offsets = arrow_data.offsets();
                            ZipValidity::new_with_validity(
                                offsets.array_windows(),
                                arrow_data.nulls(),
                            )
                            .map(|elem| {
                                elem.map(|&[start, end]| {
                                    let start = start as usize;
                                    let end = end as usize;
                                    let len = end - start;
                                    if arrow_data_buf.len() < end {
                                        return Err(DeserializationError::offset_slice_oob(
                                            (start, end),
                                            arrow_data_buf.len(),
                                        ));
                                    }
                                    let data = arrow_data_buf.slice_with_length(start, len);
                                    Ok(data)
                                })
                                .transpose()
                            })
                            .map(|res_or_opt| {
                                res_or_opt.map(|res_or_opt| {
                                    res_or_opt.map(|v| ::re_types_core::ArrowString::from(v))
                                })
                            })
                            .collect::<DeserializationResult<Vec<Option<_>>>>()
                            .with_context("rerun.encodings.TableGroup#sub_group")?
                            .into_iter()
                        }
                    };
                    let columns = {
                        if !arrays_by_name.contains_key("columns") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "columns",
                            ))
                            .with_context("rerun.encodings.TableGroup");
                        }
                        let arrow_data = &**arrays_by_name["columns"];
                        {
                            let arrow_data = arrow_data
                                .try_cast::<arrow::array::ListArray>(|| {
                                    DataType::List(std::sync::Arc::new(Field::new(
                                        "item",
                                        <crate::encodings::TableColumnSchema>::arrow_data_type(),
                                        false,
                                    )))
                                })
                                .with_context("rerun.encodings.TableGroup#columns")?;
                            if arrow_data.is_empty() {
                                Vec::new()
                            } else {
                                let arrow_data_inner = {
                                    let arrow_data_inner = &**arrow_data.values();
                                    crate::encodings::TableColumnSchema::from_arrow(
                                        arrow_data_inner,
                                    )
                                    .with_context("rerun.encodings.TableGroup#columns")?
                                    .into_iter()
                                    .map(Some)
                                    .collect::<Vec<_>>()
                                };
                                let offsets = arrow_data.offsets();
                                ZipValidity::new_with_validity(
                                    offsets.array_windows(),
                                    arrow_data.nulls(),
                                )
                                .map(|elem| {
                                    elem.map(|&[start, end]| {
                                        let start = start as usize;
                                        let end = end as usize;
                                        if arrow_data_inner.len() < end {
                                            return Err(DeserializationError::offset_slice_oob(
                                                (start, end),
                                                arrow_data_inner.len(),
                                            ));
                                        }

                                        #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                                        let data =
                                            unsafe { arrow_data_inner.get_unchecked(start..end) };
                                        let data = data
                                            .iter()
                                            .cloned()
                                            .map(Option::unwrap_or_default)
                                            .collect();
                                        Ok(data)
                                    })
                                    .transpose()
                                })
                                .collect::<DeserializationResult<Vec<Option<_>>>>()?
                            }
                            .into_iter()
                        }
                    };
                    ZipValidity::new_with_validity(
                        ::itertools::izip!(id, primary_group, sub_group, columns),
                        arrow_data.nulls(),
                    )
                    .map(|opt| {
                        opt.map(|(id, primary_group, sub_group, columns)| {
                            Ok(Self {
                                id: id
                                    .ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.encodings.TableGroup#id")?,
                                primary_group: primary_group
                                    .ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.encodings.TableGroup#primary_group")?,
                                sub_group,
                                columns: columns
                                    .ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.encodings.TableGroup#columns")?,
                            })
                        })
                        .transpose()
                    })
                    .collect::<DeserializationResult<Vec<_>>>()
                    .with_context("rerun.encodings.TableGroup")?
                }
            }
        }
        .into_iter()
        .map(|v| v.ok_or_else(DeserializationError::missing_data))
        .collect::<DeserializationResult<Vec<_>>>()?)
    }
}
