// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/encodings/table_schema.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Encoding**: The groups and display settings of a [`archetypes::DataTable`][crate::archetypes::DataTable].
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default, PartialEq, ::re_byte_size::SizeBytes)]
pub struct TableSchema {
    /// Groups in display and data order.
    pub groups: Vec<crate::encodings::TableGroup>,

    /// Scope of header-click sorting; defaults to the whole table.
    pub sort_scope: Option<crate::encodings::TableSortScope>,

    /// Number of leading columns kept visible while scrolling; defaults to one.
    pub sticky_columns: Option<u32>,
}

::re_types_core::macros::impl_into_cow!(TableSchema);

impl ::re_types_core::ArrowDataType for TableSchema {
    #[inline]
    fn arrow_data_type() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::Struct(Fields::from(vec![
            Field::new(
                "groups",
                DataType::List(std::sync::Arc::new(Field::new(
                    "item",
                    <crate::encodings::TableGroup>::arrow_data_type(),
                    false,
                ))),
                false,
            ),
            Field::new(
                "sort_scope",
                <crate::encodings::TableSortScope>::arrow_data_type(),
                true,
            ),
            Field::new("sticky_columns", DataType::UInt32, true),
        ]))
    }
}

impl ::re_types_core::ToArrow for TableSchema {
    fn to_arrow<'a>(
        data: impl IntoIterator<Item = impl Into<Cow<'a, Self>>>,
    ) -> SerializationResult<ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{
            ArrowDataType as _, ResultExt as _, ToArrow as _, ToArrowOpt as _,
            arrow_helpers::as_array_ref,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let fields = Fields::from(vec![
                Field::new(
                    "groups",
                    DataType::List(std::sync::Arc::new(Field::new(
                        "item",
                        <crate::encodings::TableGroup>::arrow_data_type(),
                        false,
                    ))),
                    false,
                ),
                Field::new(
                    "sort_scope",
                    <crate::encodings::TableSortScope>::arrow_data_type(),
                    true,
                ),
                Field::new("sticky_columns", DataType::UInt32, true),
            ]);
            let data: Vec<_> = data
                .into_iter()
                .map(|datum| {
                    let datum: Cow<'a, Self> = datum.into();
                    datum
                })
                .collect();
            let validity = None;
            as_array_ref(StructArray::new(
                fields,
                vec![
                    {
                        let (somes, groups): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.groups.clone());
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let groups_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let offsets = arrow::buffer::OffsetBuffer::<i32>::from_lengths(
                                groups
                                    .iter()
                                    .map(|opt| opt.as_ref().map_or(0, |datum| datum.len())),
                            );
                            let groups_inner_data: Vec<_> =
                                groups.into_iter().flatten().flatten().collect();
                            let groups_inner_validity = None;
                            as_array_ref(ListArray::try_new(
                                std::sync::Arc::new(Field::new(
                                    "item",
                                    <crate::encodings::TableGroup>::arrow_data_type(),
                                    false,
                                )),
                                offsets,
                                {
                                    let _: Option<arrow::buffer::NullBuffer> =
                                        groups_inner_validity;
                                    crate::encodings::TableGroup::to_arrow(groups_inner_data)?
                                },
                                groups_validity,
                            )?)
                        }
                    },
                    {
                        let (somes, sort_scope): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.sort_scope.clone()).flatten();
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let sort_scope_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        {
                            let _ = sort_scope_validity;
                            crate::encodings::TableSortScope::to_arrow_opt(sort_scope)?
                        }
                    },
                    {
                        let (somes, sticky_columns): (Vec<_>, Vec<_>) = data
                            .iter()
                            .map(|datum| {
                                let datum = Some(datum.sticky_columns.clone()).flatten();
                                (datum.is_some(), datum)
                            })
                            .unzip();
                        let sticky_columns_validity: Option<arrow::buffer::NullBuffer> = {
                            let any_nones = somes.iter().any(|some| !*some);
                            any_nones.then(|| somes.into())
                        };
                        as_array_ref(PrimitiveArray::<UInt32Type>::new(
                            sticky_columns
                                .into_iter()
                                .map(|v| v.unwrap_or_default())
                                .collect(),
                            sticky_columns_validity,
                        ))
                    },
                ],
                validity,
            ))
        })
    }
}

impl ::re_types_core::FromArrow for TableSchema {
    fn from_arrow(arrow_data: &dyn arrow::array::Array) -> DeserializationResult<Vec<Self>> {
        use ::re_types_core::{
            ArrowDataType as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
            arrow_helpers::*, arrow_zip_validity::ZipValidity,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        err_on_nulls(arrow_data, "rerun.encodings.TableSchema")?;
        Ok({
            {
                let arrow_data = arrow_data
                    .try_cast::<arrow::array::StructArray>(|| Self::arrow_data_type())
                    .with_context("rerun.encodings.TableSchema")?;
                if arrow_data.is_empty() {
                    Vec::new()
                } else {
                    let (arrow_data_fields, arrow_data_arrays) =
                        (arrow_data.fields(), arrow_data.columns());
                    let arrays_by_name: ::std::collections::HashMap<_, _> = ::std::iter::zip(
                        arrow_data_fields.iter().map(|field| field.name().as_str()),
                        arrow_data_arrays,
                    )
                    .collect();
                    let groups = {
                        if !arrays_by_name.contains_key("groups") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "groups",
                            ))
                            .with_context("rerun.encodings.TableSchema");
                        }
                        let arrow_data = &**arrays_by_name["groups"];
                        {
                            let arrow_data = arrow_data
                                .try_cast::<arrow::array::ListArray>(|| {
                                    DataType::List(std::sync::Arc::new(Field::new(
                                        "item",
                                        <crate::encodings::TableGroup>::arrow_data_type(),
                                        false,
                                    )))
                                })
                                .with_context("rerun.encodings.TableSchema#groups")?;
                            if arrow_data.is_empty() {
                                Vec::new()
                            } else {
                                let arrow_data_inner = {
                                    let arrow_data_inner = &**arrow_data.values();
                                    crate::encodings::TableGroup::from_arrow(arrow_data_inner)
                                        .with_context("rerun.encodings.TableSchema#groups")?
                                        .into_iter()
                                        .map(Some)
                                        .collect::<Vec<_>>()
                                };
                                let offsets = arrow_data.offsets();
                                ZipValidity::new_with_validity(
                                    offsets.array_windows(),
                                    arrow_data.nulls(),
                                )
                                .map(|elem| {
                                    elem.map(|&[start, end]| {
                                        let start = start as usize;
                                        let end = end as usize;
                                        if arrow_data_inner.len() < end {
                                            return Err(DeserializationError::offset_slice_oob(
                                                (start, end),
                                                arrow_data_inner.len(),
                                            ));
                                        }

                                        #[expect(unsafe_code, clippy::undocumented_unsafe_blocks)]
                                        let data =
                                            unsafe { arrow_data_inner.get_unchecked(start..end) };
                                        let data = data
                                            .iter()
                                            .cloned()
                                            .map(Option::unwrap_or_default)
                                            .collect();
                                        Ok(data)
                                    })
                                    .transpose()
                                })
                                .collect::<DeserializationResult<Vec<Option<_>>>>()?
                            }
                            .into_iter()
                        }
                    };
                    let sort_scope = {
                        if !arrays_by_name.contains_key("sort_scope") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "sort_scope",
                            ))
                            .with_context("rerun.encodings.TableSchema");
                        }
                        let arrow_data = &**arrays_by_name["sort_scope"];
                        crate::encodings::TableSortScope::from_arrow_opt(arrow_data)
                            .with_context("rerun.encodings.TableSchema#sort_scope")?
                            .into_iter()
                    };
                    let sticky_columns = {
                        if !arrays_by_name.contains_key("sticky_columns") {
                            return Err(DeserializationError::missing_struct_field(
                                Self::arrow_data_type(),
                                "sticky_columns",
                            ))
                            .with_context("rerun.encodings.TableSchema");
                        }
                        let arrow_data = &**arrays_by_name["sticky_columns"];
                        arrow_data
                            .try_cast::<UInt32Array>(|| DataType::UInt32)
                            .with_context("rerun.encodings.TableSchema#sticky_columns")?
                            .into_iter()
                    };
                    ZipValidity::new_with_validity(
                        ::itertools::izip!(groups, sort_scope, sticky_columns),
                        arrow_data.nulls(),
                    )
                    .map(|opt| {
                        opt.map(|(groups, sort_scope, sticky_columns)| {
                            Ok(Self {
                                groups: groups
                                    .ok_or_else(DeserializationError::missing_data)
                                    .with_context("rerun.encodings.TableSchema#groups")?,
                                sort_scope,
                                sticky_columns,
                            })
                        })
                        .transpose()
                    })
                    .collect::<DeserializationResult<Vec<_>>>()
                    .with_context("rerun.encodings.TableSchema")?
                }
            }
        }
        .into_iter()
        .map(|v| v.ok_or_else(DeserializationError::missing_data))
        .collect::<DeserializationResult<Vec<_>>>()?)
    }
}
